/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[7] = {4, 2, 0, 1, 2, 2, 3};
static const casadi_int casadi_s1[9] = {2, 4, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s2[11] = {4, 2, 0, 3, 6, 0, 1, 2, 0, 1, 3};
static const casadi_int casadi_s3[9] = {4, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s6[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[15] = {4, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};

/* point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4,8nz],o2[4x2,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, *w2=w+21, *w3=w+25, *w4=w+29, *w5=w+33, w6, *w7=w+38, *w9=w+40, *w10=w+42, *w11=w+44, *w12=w+50, *w13=w+58;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[3][1] */
  w0 = arg[3] ? arg[3][1] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #8: @1 = input[1][0] */
  casadi_copy(arg[1], 16, w1);
  /* #9: {@2, @3, @4, @5} = horzsplit(@1) */
  casadi_copy(w1, 4, w2);
  casadi_copy(w1+4, 4, w3);
  casadi_copy(w1+8, 4, w4);
  casadi_copy(w1+12, 4, w5);
  /* #10: {NULL, NULL, @0, @6} = vertsplit(@2) */
  w0 = w2[2];
  w6 = w2[3];
  /* #11: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #12: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #13: {NULL, NULL, @6, @0} = vertsplit(@3) */
  w6 = w3[2];
  w0 = w3[3];
  /* #14: output[1][2] = @6 */
  if (res[1]) res[1][2] = w6;
  /* #15: output[1][3] = @0 */
  if (res[1]) res[1][3] = w0;
  /* #16: {NULL, NULL, @0, @6} = vertsplit(@4) */
  w0 = w4[2];
  w6 = w4[3];
  /* #17: output[1][4] = @0 */
  if (res[1]) res[1][4] = w0;
  /* #18: output[1][5] = @6 */
  if (res[1]) res[1][5] = w6;
  /* #19: {NULL, NULL, @6, @0} = vertsplit(@5) */
  w6 = w5[2];
  w0 = w5[3];
  /* #20: output[1][6] = @6 */
  if (res[1]) res[1][6] = w6;
  /* #21: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #22: @7 = zeros(2x4,2nz) */
  casadi_clear(w7, 2);
  /* #23: @8 = 00 */
  /* #24: @9 = ones(2x1) */
  casadi_fill(w9, 2, 1.);
  /* #25: {@0, @6} = vertsplit(@9) */
  w0 = w9[0];
  w6 = w9[1];
  /* #26: @9 = vertcat(@8, @8, @0, @6) */
  rr=w9;
  *rr++ = w0;
  *rr++ = w6;
  /* #27: @10 = @9[:2] */
  for (rr=w10, ss=w9+0; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #28: (@7[:2] = @10) */
  for (rr=w7+0, ss=w10; rr!=w7+2; rr+=1) *rr = *ss++;
  /* #29: @10 = @7' */
  casadi_trans(w7,casadi_s1, w10, casadi_s0, iw);
  /* #30: @11 = project(@10) */
  casadi_project(w10, casadi_s0, w11, casadi_s2, w);
  /* #31: @12 = input[2][0] */
  casadi_copy(arg[2], 8, w12);
  /* #32: {@5, @4} = horzsplit(@12) */
  casadi_copy(w12, 4, w5);
  casadi_copy(w12+4, 4, w4);
  /* #33: {NULL, NULL, @0, @6} = vertsplit(@5) */
  w0 = w5[2];
  w6 = w5[3];
  /* #34: @10 = vertcat(@0, @6, @8, @8) */
  rr=w10;
  *rr++ = w0;
  *rr++ = w6;
  /* #35: {NULL, NULL, @0, @6} = vertsplit(@4) */
  w0 = w4[2];
  w6 = w4[3];
  /* #36: @7 = vertcat(@0, @6, @8, @8) */
  rr=w7;
  *rr++ = w0;
  *rr++ = w6;
  /* #37: @4 = horzcat(@10, @7) */
  rr=w4;
  for (i=0, cs=w10; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<2; ++i) *rr++ = *cs++;
  /* #38: @13 = project(@4) */
  casadi_project(w4, casadi_s3, w13, casadi_s2, w);
  /* #39: @11 = (@11+@13) */
  for (i=0, rr=w11, cs=w13; i<6; ++i) (*rr++) += (*cs++);
  /* #40: output[2][0] = @11 */
  casadi_copy(w11, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 64;
  return 0;
}

CASADI_SYMBOL_EXPORT int point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 64*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
