/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun:(i0[8],i1[2],i2[],i3[],i4[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+16, *w13=w+20, *w14=w+24;
  /* #0: @0 = 0.125 */
  w0 = 1.2500000000000000e-01;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #21: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #22: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #23: @4 = (-@2) */
  w4 = (- w2 );
  /* #24: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #25: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #26: @4 = (@4-@5) */
  w4 -= w5;
  /* #27: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #28: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #29: @4 = (@4-@7) */
  w4 -= w7;
  /* #30: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #31: @0 = (@0*@9) */
  w0 *= w9;
  /* #32: @4 = (@4-@0) */
  w4 -= w0;
  /* #33: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #34: @4 = 0 */
  w4 = 0.;
  /* #35: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #36: @12 = @1; (@12[3] += @0) */
  casadi_copy(w1, 4, w12);
  for (rr=w12+3, ss=(&w0); rr!=w12+4; rr+=1) *rr += *ss++;
  /* #37: @0 = (@0+@7) */
  w0 += w7;
  /* #38: (@12[2] += @0) */
  for (rr=w12+2, ss=(&w0); rr!=w12+3; rr+=1) *rr += *ss++;
  /* #39: @0 = (@0+@5) */
  w0 += w5;
  /* #40: (@12[1] += @0) */
  for (rr=w12+1, ss=(&w0); rr!=w12+2; rr+=1) *rr += *ss++;
  /* #41: @0 = (@0+@2) */
  w0 += w2;
  /* #42: (@12[0] += @0) */
  for (rr=w12+0, ss=(&w0); rr!=w12+1; rr+=1) *rr += *ss++;
  /* #43: @0 = @12[0] */
  for (rr=(&w0), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #44: @13 = @1; (@13[0] = @0) */
  casadi_copy(w1, 4, w13);
  for (rr=w13+0, ss=(&w0); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #45: @0 = @12[1] */
  for (rr=(&w0), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #46: (@13[1] = @0) */
  for (rr=w13+1, ss=(&w0); rr!=w13+2; rr+=1) *rr = *ss++;
  /* #47: @0 = @12[2] */
  for (rr=(&w0), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #48: (@13[2] = @0) */
  for (rr=w13+2, ss=(&w0); rr!=w13+3; rr+=1) *rr = *ss++;
  /* #49: @0 = @12[3] */
  for (rr=(&w0), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #50: (@13[3] = @0) */
  for (rr=w13+3, ss=(&w0); rr!=w13+4; rr+=1) *rr = *ss++;
  /* #51: @13 = @13' */
  /* #52: @12 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 4, w12);
  /* #53: @0 = mac(@13,@12,@4) */
  casadi_copy((&w4), 1, (&w0));
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w13+j, tt=w12+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #54: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #55: @0 = -0.125 */
  w0 = -1.2500000000000000e-01;
  /* #56: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #57: @2 = (-@10) */
  w2 = (- w10 );
  /* #58: @13 = @1; (@13[3] += @2) */
  casadi_copy(w1, 4, w13);
  for (rr=w13+3, ss=(&w2); rr!=w13+4; rr+=1) *rr += *ss++;
  /* #59: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #60: @8 = (-@8) */
  w8 = (- w8 );
  /* #61: @8 = (@8-@10) */
  w8 -= w10;
  /* #62: (@13[2] += @8) */
  for (rr=w13+2, ss=(&w8); rr!=w13+3; rr+=1) *rr += *ss++;
  /* #63: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #64: @8 = (@8-@6) */
  w8 -= w6;
  /* #65: (@13[1] += @8) */
  for (rr=w13+1, ss=(&w8); rr!=w13+2; rr+=1) *rr += *ss++;
  /* #66: @0 = (@0*@3) */
  w0 *= w3;
  /* #67: @8 = (@8-@0) */
  w8 -= w0;
  /* #68: (@13[0] += @8) */
  for (rr=w13+0, ss=(&w8); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #69: @8 = @13[0] */
  for (rr=(&w8), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #70: (@1[0] = @8) */
  for (rr=w1+0, ss=(&w8); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #71: @8 = @13[1] */
  for (rr=(&w8), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #72: (@1[1] = @8) */
  for (rr=w1+1, ss=(&w8); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #73: @8 = @13[2] */
  for (rr=(&w8), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #74: (@1[2] = @8) */
  for (rr=w1+2, ss=(&w8); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #75: @8 = @13[3] */
  for (rr=(&w8), ss=w13+3; ss!=w13+4; ss+=1) *rr++ = *ss;
  /* #76: (@1[3] = @8) */
  for (rr=w1+3, ss=(&w8); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #77: @1 = @1' */
  /* #78: @4 = mac(@1,@12,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #79: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #80: @14 = input[1][0] */
  casadi_copy(arg[1], 2, w14);
  /* #81: output[0][4] = @14 */
  if (res[0]) casadi_copy(w14, 2, res[0]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 26*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
