/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[6] = {0, 4, 8, 16, 24, 25};
static const casadi_int casadi_s1[4] = {1, 5, 9, 17};
static const casadi_int casadi_s2[4] = {2, 6, 10, 18};
static const casadi_int casadi_s3[4] = {3, 7, 11, 19};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s6[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s14[35] = {10, 6, 0, 4, 8, 16, 24, 25, 26, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1};
static const casadi_int casadi_s15[3] = {6, 0, 0};

/* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt:(i0[8],i1[2],i2[],i3[],i4[])->(o0[6],o1[10x6,26nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+19, *w16=w+23, *w17=w+27, *w18=w+31, *w19=w+35, *w20=w+37, *w21=w+63, w22, w23, w24, w25, w26, w27, *w28=w+72, *w29=w+76, *w32=w+82;
  /* #0: @0 = 0.125 */
  w0 = 1.2500000000000000e-01;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #21: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #22: @4 = (@0*@2) */
  w4  = (w0*w2);
  /* #23: @11 = (-@4) */
  w11 = (- w4 );
  /* #24: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #25: @12 = (@0*@5) */
  w12  = (w0*w5);
  /* #26: @11 = (@11-@12) */
  w11 -= w12;
  /* #27: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #28: @13 = (@0*@7) */
  w13  = (w0*w7);
  /* #29: @11 = (@11-@13) */
  w11 -= w13;
  /* #30: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #31: @14 = (@0*@9) */
  w14  = (w0*w9);
  /* #32: @11 = (@11-@14) */
  w11 -= w14;
  /* #33: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #34: @11 = 0 */
  w11 = 0.;
  /* #35: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #36: @15 = @1; (@15[3] += @14) */
  casadi_copy(w1, 4, w15);
  for (rr=w15+3, ss=(&w14); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #37: @14 = (@14+@13) */
  w14 += w13;
  /* #38: (@15[2] += @14) */
  for (rr=w15+2, ss=(&w14); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #39: @14 = (@14+@12) */
  w14 += w12;
  /* #40: (@15[1] += @14) */
  for (rr=w15+1, ss=(&w14); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #41: @14 = (@14+@4) */
  w14 += w4;
  /* #42: (@15[0] += @14) */
  for (rr=w15+0, ss=(&w14); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #43: @14 = @15[0] */
  for (rr=(&w14), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #44: @16 = @1; (@16[0] = @14) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+0, ss=(&w14); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #45: @14 = @15[1] */
  for (rr=(&w14), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #46: (@16[1] = @14) */
  for (rr=w16+1, ss=(&w14); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #47: @14 = @15[2] */
  for (rr=(&w14), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #48: (@16[2] = @14) */
  for (rr=w16+2, ss=(&w14); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #49: @14 = @15[3] */
  for (rr=(&w14), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #50: (@16[3] = @14) */
  for (rr=w16+3, ss=(&w14); rr!=w16+4; rr+=1) *rr = *ss++;
  /* #51: @16 = @16' */
  /* #52: @15 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 4, w15);
  /* #53: @14 = mac(@16,@15,@11) */
  casadi_copy((&w11), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #54: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #55: @14 = -0.125 */
  w14 = -1.2500000000000000e-01;
  /* #56: @4 = (@14*@10) */
  w4  = (w14*w10);
  /* #57: @12 = (-@4) */
  w12 = (- w4 );
  /* #58: @17 = @1; (@17[3] += @12) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w12); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #59: @12 = (@14*@8) */
  w12  = (w14*w8);
  /* #60: @12 = (-@12) */
  w12 = (- w12 );
  /* #61: @12 = (@12-@4) */
  w12 -= w4;
  /* #62: (@17[2] += @12) */
  for (rr=w17+2, ss=(&w12); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #63: @4 = (@14*@6) */
  w4  = (w14*w6);
  /* #64: @12 = (@12-@4) */
  w12 -= w4;
  /* #65: (@17[1] += @12) */
  for (rr=w17+1, ss=(&w12); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #66: @4 = (@14*@3) */
  w4  = (w14*w3);
  /* #67: @12 = (@12-@4) */
  w12 -= w4;
  /* #68: (@17[0] += @12) */
  for (rr=w17+0, ss=(&w12); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #69: @12 = @17[0] */
  for (rr=(&w12), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #70: @18 = @1; (@18[0] = @12) */
  casadi_copy(w1, 4, w18);
  for (rr=w18+0, ss=(&w12); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #71: @12 = @17[1] */
  for (rr=(&w12), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #72: (@18[1] = @12) */
  for (rr=w18+1, ss=(&w12); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #73: @12 = @17[2] */
  for (rr=(&w12), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #74: (@18[2] = @12) */
  for (rr=w18+2, ss=(&w12); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #75: @12 = @17[3] */
  for (rr=(&w12), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #76: (@18[3] = @12) */
  for (rr=w18+3, ss=(&w12); rr!=w18+4; rr+=1) *rr = *ss++;
  /* #77: @18 = @18' */
  /* #78: @12 = mac(@18,@15,@11) */
  casadi_copy((&w11), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #79: output[0][3] = @12 */
  if (res[0]) res[0][3] = w12;
  /* #80: @19 = input[1][0] */
  casadi_copy(arg[1], 2, w19);
  /* #81: output[0][4] = @19 */
  if (res[0]) casadi_copy(w19, 2, res[0]+4);
  /* #82: @20 = zeros(10x6,26nz) */
  casadi_clear(w20, 26);
  /* #83: @21 = ones(10x1,3nz) */
  casadi_fill(w21, 3, 1.);
  /* #84: {@19, @12, NULL} = vertsplit(@21) */
  casadi_copy(w21, 2, w19);
  w12 = w21[2];
  /* #85: @4 = @12[0] */
  for (rr=(&w4), ss=(&w12)+0; ss!=(&w12)+1; ss+=1) *rr++ = *ss;
  /* #86: @2 = (@2*@4) */
  w2 *= w4;
  /* #87: @12 = (@0*@2) */
  w12  = (w0*w2);
  /* #88: @13 = (@5*@4) */
  w13  = (w5*w4);
  /* #89: @22 = (@0*@13) */
  w22  = (w0*w13);
  /* #90: @12 = (@12+@22) */
  w12 += w22;
  /* #91: @22 = (@7*@4) */
  w22  = (w7*w4);
  /* #92: @23 = (@0*@22) */
  w23  = (w0*w22);
  /* #93: @12 = (@12+@23) */
  w12 += w23;
  /* #94: @23 = (@9*@4) */
  w23  = (w9*w4);
  /* #95: @24 = (@0*@23) */
  w24  = (w0*w23);
  /* #96: @12 = (@12+@24) */
  w12 += w24;
  /* #97: @3 = (@3*@4) */
  w3 *= w4;
  /* #98: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #99: @24 = (@6*@4) */
  w24  = (w6*w4);
  /* #100: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #101: @25 = (@3+@24) */
  w25  = (w3+w24);
  /* #102: @26 = (@8*@4) */
  w26  = (w8*w4);
  /* #103: @26 = (@0*@26) */
  w26  = (w0*w26);
  /* #104: @25 = (@25+@26) */
  w25 += w26;
  /* #105: @4 = (@10*@4) */
  w4  = (w10*w4);
  /* #106: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #107: @25 = (@25+@4) */
  w25 += w4;
  /* #108: @27 = (-@4) */
  w27 = (- w4 );
  /* #109: @17 = @1; (@17[3] += @27) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w27); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #110: @26 = (-@26) */
  w26 = (- w26 );
  /* #111: @26 = (@26-@4) */
  w26 -= w4;
  /* #112: (@17[2] += @26) */
  for (rr=w17+2, ss=(&w26); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #113: @26 = (@26-@24) */
  w26 -= w24;
  /* #114: (@17[1] += @26) */
  for (rr=w17+1, ss=(&w26); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #115: @26 = (@26-@3) */
  w26 -= w3;
  /* #116: (@17[0] += @26) */
  for (rr=w17+0, ss=(&w26); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #117: @26 = @17[0] */
  for (rr=(&w26), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #118: @28 = @1; (@28[0] += @26) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+0, ss=(&w26); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #119: (@28[1] = @11) */
  for (rr=w28+1, ss=(&w11); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #120: @26 = @17[1] */
  for (rr=(&w26), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #121: (@28[1] += @26) */
  for (rr=w28+1, ss=(&w26); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #122: (@28[2] = @11) */
  for (rr=w28+2, ss=(&w11); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #123: @26 = @17[2] */
  for (rr=(&w26), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #124: (@28[2] += @26) */
  for (rr=w28+2, ss=(&w26); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #125: (@28[3] = @11) */
  for (rr=w28+3, ss=(&w11); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #126: @26 = @17[3] */
  for (rr=(&w26), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #127: (@28[3] += @26) */
  for (rr=w28+3, ss=(&w26); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #128: @28 = @28' */
  /* #129: @26 = mac(@28,@15,@11) */
  casadi_copy((&w11), 1, (&w26));
  for (i=0, rr=(&w26); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #130: @23 = (@14*@23) */
  w23  = (w14*w23);
  /* #131: @23 = (-@23) */
  w23 = (- w23 );
  /* #132: @28 = @1; (@28[3] += @23) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+3, ss=(&w23); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #133: @22 = (@14*@22) */
  w22  = (w14*w22);
  /* #134: @23 = (@23-@22) */
  w23 -= w22;
  /* #135: (@28[2] += @23) */
  for (rr=w28+2, ss=(&w23); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #136: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #137: @23 = (@23-@13) */
  w23 -= w13;
  /* #138: (@28[1] += @23) */
  for (rr=w28+1, ss=(&w23); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #139: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #140: @23 = (@23-@2) */
  w23 -= w2;
  /* #141: (@28[0] += @23) */
  for (rr=w28+0, ss=(&w23); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #142: @23 = @28[0] */
  for (rr=(&w23), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #143: @17 = @1; (@17[0] += @23) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w23); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #144: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #145: @23 = @28[1] */
  for (rr=(&w23), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #146: (@17[1] += @23) */
  for (rr=w17+1, ss=(&w23); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #147: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #148: @23 = @28[2] */
  for (rr=(&w23), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #149: (@17[2] += @23) */
  for (rr=w17+2, ss=(&w23); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #150: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #151: @23 = @28[3] */
  for (rr=(&w23), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #152: (@17[3] += @23) */
  for (rr=w17+3, ss=(&w23); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #153: @17 = @17' */
  /* #154: @23 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w23));
  for (i=0, rr=(&w23); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #155: @29 = vertcat(@12, @25, @26, @23, @19) */
  rr=w29;
  *rr++ = w12;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w23;
  for (i=0, cs=w19; i<2; ++i) *rr++ = *cs++;
  /* #156: (@20[0, 4, 8, 16, 24, 25] = @29) */
  for (cii=casadi_s0, rr=w20, ss=w29; cii!=casadi_s0+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #157: @12 = ones(10x1,1nz) */
  w12 = 1.;
  /* #158: {NULL, @25, NULL} = vertsplit(@12) */
  w25 = w12;
  /* #159: @12 = @25[0] */
  for (rr=(&w12), ss=(&w25)+0; ss!=(&w25)+1; ss+=1) *rr++ = *ss;
  /* #160: @5 = (@5*@12) */
  w5 *= w12;
  /* #161: @25 = (@0*@5) */
  w25  = (w0*w5);
  /* #162: @26 = (@7*@12) */
  w26  = (w7*w12);
  /* #163: @23 = (@0*@26) */
  w23  = (w0*w26);
  /* #164: @25 = (@25+@23) */
  w25 += w23;
  /* #165: @23 = (@9*@12) */
  w23  = (w9*w12);
  /* #166: @2 = (@0*@23) */
  w2  = (w0*w23);
  /* #167: @25 = (@25+@2) */
  w25 += w2;
  /* #168: @6 = (@6*@12) */
  w6 *= w12;
  /* #169: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #170: @2 = (@8*@12) */
  w2  = (w8*w12);
  /* #171: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #172: @13 = (@6+@2) */
  w13  = (w6+w2);
  /* #173: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #174: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #175: @13 = (@13+@12) */
  w13 += w12;
  /* #176: @22 = (-@12) */
  w22 = (- w12 );
  /* #177: @17 = @1; (@17[3] += @22) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w22); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #178: @2 = (-@2) */
  w2 = (- w2 );
  /* #179: @2 = (@2-@12) */
  w2 -= w12;
  /* #180: (@17[2] += @2) */
  for (rr=w17+2, ss=(&w2); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #181: @2 = (@2-@6) */
  w2 -= w6;
  /* #182: (@17[1] += @2) */
  for (rr=w17+1, ss=(&w2); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #183: (@17[0] += @2) */
  for (rr=w17+0, ss=(&w2); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #184: @2 = @17[0] */
  for (rr=(&w2), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #185: @28 = @1; (@28[0] += @2) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+0, ss=(&w2); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #186: (@28[1] = @11) */
  for (rr=w28+1, ss=(&w11); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #187: @2 = @17[1] */
  for (rr=(&w2), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #188: (@28[1] += @2) */
  for (rr=w28+1, ss=(&w2); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #189: (@28[2] = @11) */
  for (rr=w28+2, ss=(&w11); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #190: @2 = @17[2] */
  for (rr=(&w2), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #191: (@28[2] += @2) */
  for (rr=w28+2, ss=(&w2); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #192: (@28[3] = @11) */
  for (rr=w28+3, ss=(&w11); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #193: @2 = @17[3] */
  for (rr=(&w2), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #194: (@28[3] += @2) */
  for (rr=w28+3, ss=(&w2); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #195: @28 = @28' */
  /* #196: @2 = mac(@28,@15,@11) */
  casadi_copy((&w11), 1, (&w2));
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #197: @23 = (@14*@23) */
  w23  = (w14*w23);
  /* #198: @23 = (-@23) */
  w23 = (- w23 );
  /* #199: @28 = @1; (@28[3] += @23) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+3, ss=(&w23); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #200: @26 = (@14*@26) */
  w26  = (w14*w26);
  /* #201: @23 = (@23-@26) */
  w23 -= w26;
  /* #202: (@28[2] += @23) */
  for (rr=w28+2, ss=(&w23); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #203: @5 = (@14*@5) */
  w5  = (w14*w5);
  /* #204: @23 = (@23-@5) */
  w23 -= w5;
  /* #205: (@28[1] += @23) */
  for (rr=w28+1, ss=(&w23); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #206: (@28[0] += @23) */
  for (rr=w28+0, ss=(&w23); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #207: @23 = @28[0] */
  for (rr=(&w23), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #208: @17 = @1; (@17[0] += @23) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w23); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #209: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #210: @23 = @28[1] */
  for (rr=(&w23), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #211: (@17[1] += @23) */
  for (rr=w17+1, ss=(&w23); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #212: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #213: @23 = @28[2] */
  for (rr=(&w23), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #214: (@17[2] += @23) */
  for (rr=w17+2, ss=(&w23); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #215: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #216: @23 = @28[3] */
  for (rr=(&w23), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #217: (@17[3] += @23) */
  for (rr=w17+3, ss=(&w23); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #218: @17 = @17' */
  /* #219: @23 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w23));
  for (i=0, rr=(&w23); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #220: @30 = zeros(2x1,0nz) */
  /* #221: @17 = vertcat(@25, @13, @2, @23, @30) */
  rr=w17;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w2;
  *rr++ = w23;
  /* #222: @28 = @17[:4] */
  for (rr=w28, ss=w17+0; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #223: (@20[1, 5, 9, 17] = @28) */
  for (cii=casadi_s1, rr=w20, ss=w28; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #224: @25 = ones(10x1,1nz) */
  w25 = 1.;
  /* #225: {NULL, @13, NULL} = vertsplit(@25) */
  w13 = w25;
  /* #226: @25 = @13[0] */
  for (rr=(&w25), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #227: @7 = (@7*@25) */
  w7 *= w25;
  /* #228: @13 = (@0*@7) */
  w13  = (w0*w7);
  /* #229: @2 = (@9*@25) */
  w2  = (w9*w25);
  /* #230: @23 = (@0*@2) */
  w23  = (w0*w2);
  /* #231: @13 = (@13+@23) */
  w13 += w23;
  /* #232: @8 = (@8*@25) */
  w8 *= w25;
  /* #233: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #234: @25 = (@10*@25) */
  w25  = (w10*w25);
  /* #235: @25 = (@0*@25) */
  w25  = (w0*w25);
  /* #236: @23 = (@8+@25) */
  w23  = (w8+w25);
  /* #237: @5 = (-@25) */
  w5 = (- w25 );
  /* #238: @28 = @1; (@28[3] += @5) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+3, ss=(&w5); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #239: @8 = (-@8) */
  w8 = (- w8 );
  /* #240: @8 = (@8-@25) */
  w8 -= w25;
  /* #241: (@28[2] += @8) */
  for (rr=w28+2, ss=(&w8); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #242: (@28[1] += @8) */
  for (rr=w28+1, ss=(&w8); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #243: (@28[0] += @8) */
  for (rr=w28+0, ss=(&w8); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #244: @8 = @28[0] */
  for (rr=(&w8), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #245: @17 = @1; (@17[0] += @8) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w8); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #246: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #247: @8 = @28[1] */
  for (rr=(&w8), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #248: (@17[1] += @8) */
  for (rr=w17+1, ss=(&w8); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #249: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #250: @8 = @28[2] */
  for (rr=(&w8), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #251: (@17[2] += @8) */
  for (rr=w17+2, ss=(&w8); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #252: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #253: @8 = @28[3] */
  for (rr=(&w8), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #254: (@17[3] += @8) */
  for (rr=w17+3, ss=(&w8); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #255: @17 = @17' */
  /* #256: @8 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w8));
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #257: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #258: @2 = (-@2) */
  w2 = (- w2 );
  /* #259: @17 = @1; (@17[3] += @2) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w2); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #260: @7 = (@14*@7) */
  w7  = (w14*w7);
  /* #261: @2 = (@2-@7) */
  w2 -= w7;
  /* #262: (@17[2] += @2) */
  for (rr=w17+2, ss=(&w2); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #263: (@17[1] += @2) */
  for (rr=w17+1, ss=(&w2); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #264: (@17[0] += @2) */
  for (rr=w17+0, ss=(&w2); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #265: @2 = @17[0] */
  for (rr=(&w2), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #266: @28 = @1; (@28[0] += @2) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+0, ss=(&w2); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #267: (@28[1] = @11) */
  for (rr=w28+1, ss=(&w11); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #268: @2 = @17[1] */
  for (rr=(&w2), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #269: (@28[1] += @2) */
  for (rr=w28+1, ss=(&w2); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #270: (@28[2] = @11) */
  for (rr=w28+2, ss=(&w11); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #271: @2 = @17[2] */
  for (rr=(&w2), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #272: (@28[2] += @2) */
  for (rr=w28+2, ss=(&w2); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #273: (@28[3] = @11) */
  for (rr=w28+3, ss=(&w11); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #274: @2 = @17[3] */
  for (rr=(&w2), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #275: (@28[3] += @2) */
  for (rr=w28+3, ss=(&w2); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #276: @28 = @28' */
  /* #277: @2 = mac(@28,@15,@11) */
  casadi_copy((&w11), 1, (&w2));
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #278: @28 = vertcat(@13, @23, @8, @2, @30) */
  rr=w28;
  *rr++ = w13;
  *rr++ = w23;
  *rr++ = w8;
  *rr++ = w2;
  /* #279: @17 = @28[:4] */
  for (rr=w17, ss=w28+0; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #280: (@20[2, 6, 10, 18] = @17) */
  for (cii=casadi_s2, rr=w20, ss=w17; cii!=casadi_s2+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #281: @13 = ones(10x1,1nz) */
  w13 = 1.;
  /* #282: {NULL, @23, NULL} = vertsplit(@13) */
  w23 = w13;
  /* #283: @13 = @23[0] */
  for (rr=(&w13), ss=(&w23)+0; ss!=(&w23)+1; ss+=1) *rr++ = *ss;
  /* #284: @9 = (@9*@13) */
  w9 *= w13;
  /* #285: @23 = (@0*@9) */
  w23  = (w0*w9);
  /* #286: @10 = (@10*@13) */
  w10 *= w13;
  /* #287: @0 = (@0*@10) */
  w0 *= w10;
  /* #288: @10 = (-@0) */
  w10 = (- w0 );
  /* #289: @17 = @1; (@17[3] += @10) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w10); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #290: (@17[2] += @10) */
  for (rr=w17+2, ss=(&w10); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #291: (@17[1] += @10) */
  for (rr=w17+1, ss=(&w10); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #292: (@17[0] += @10) */
  for (rr=w17+0, ss=(&w10); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #293: @10 = @17[0] */
  for (rr=(&w10), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #294: @28 = @1; (@28[0] += @10) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+0, ss=(&w10); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #295: (@28[1] = @11) */
  for (rr=w28+1, ss=(&w11); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #296: @10 = @17[1] */
  for (rr=(&w10), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #297: (@28[1] += @10) */
  for (rr=w28+1, ss=(&w10); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #298: (@28[2] = @11) */
  for (rr=w28+2, ss=(&w11); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #299: @10 = @17[2] */
  for (rr=(&w10), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #300: (@28[2] += @10) */
  for (rr=w28+2, ss=(&w10); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #301: (@28[3] = @11) */
  for (rr=w28+3, ss=(&w11); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #302: @10 = @17[3] */
  for (rr=(&w10), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #303: (@28[3] += @10) */
  for (rr=w28+3, ss=(&w10); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #304: @28 = @28' */
  /* #305: @10 = mac(@28,@15,@11) */
  casadi_copy((&w11), 1, (&w10));
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #306: @14 = (@14*@9) */
  w14 *= w9;
  /* #307: @14 = (-@14) */
  w14 = (- w14 );
  /* #308: @28 = @1; (@28[3] += @14) */
  casadi_copy(w1, 4, w28);
  for (rr=w28+3, ss=(&w14); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #309: (@28[2] += @14) */
  for (rr=w28+2, ss=(&w14); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #310: (@28[1] += @14) */
  for (rr=w28+1, ss=(&w14); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #311: (@28[0] += @14) */
  for (rr=w28+0, ss=(&w14); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #312: @14 = @28[0] */
  for (rr=(&w14), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #313: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #314: (@1[1] = @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #315: @14 = @28[1] */
  for (rr=(&w14), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #316: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #317: (@1[2] = @11) */
  for (rr=w1+2, ss=(&w11); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #318: @14 = @28[2] */
  for (rr=(&w14), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #319: (@1[2] += @14) */
  for (rr=w1+2, ss=(&w14); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #320: (@1[3] = @11) */
  for (rr=w1+3, ss=(&w11); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #321: @14 = @28[3] */
  for (rr=(&w14), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #322: (@1[3] += @14) */
  for (rr=w1+3, ss=(&w14); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #323: @1 = @1' */
  /* #324: @14 = mac(@1,@15,@11) */
  casadi_copy((&w11), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #325: @1 = vertcat(@23, @0, @10, @14, @30) */
  rr=w1;
  *rr++ = w23;
  *rr++ = w0;
  *rr++ = w10;
  *rr++ = w14;
  /* #326: @15 = @1[:4] */
  for (rr=w15, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #327: (@20[3, 7, 11, 19] = @15) */
  for (cii=casadi_s3, rr=w20, ss=w15; cii!=casadi_s3+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #328: @31 = 00 */
  /* #329: @23 = ones(10x1,1nz) */
  w23 = 1.;
  /* #330: {NULL, NULL, @0} = vertsplit(@23) */
  w0 = w23;
  /* #331: @23 = mac(@16,@0,@11) */
  casadi_copy((&w11), 1, (&w23));
  casadi_mtimes(w16, casadi_s6, (&w0), casadi_s5, (&w23), casadi_s4, w, 0);
  /* #332: @10 = mac(@18,@0,@11) */
  casadi_copy((&w11), 1, (&w10));
  casadi_mtimes(w18, casadi_s6, (&w0), casadi_s5, (&w10), casadi_s4, w, 0);
  /* #333: @19 = vertcat(@31, @31, @23, @10, @30) */
  rr=w19;
  *rr++ = w23;
  *rr++ = w10;
  /* #334: @32 = @19[:2] */
  for (rr=w32, ss=w19+0; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #335: (@20[12:28:8] = @32) */
  for (rr=w20+12, ss=w32; rr!=w20+28; rr+=8) *rr = *ss++;
  /* #336: @23 = ones(10x1,1nz) */
  w23 = 1.;
  /* #337: {NULL, NULL, @10} = vertsplit(@23) */
  w10 = w23;
  /* #338: @23 = mac(@16,@10,@11) */
  casadi_copy((&w11), 1, (&w23));
  casadi_mtimes(w16, casadi_s6, (&w10), casadi_s7, (&w23), casadi_s4, w, 0);
  /* #339: @0 = mac(@18,@10,@11) */
  casadi_copy((&w11), 1, (&w0));
  casadi_mtimes(w18, casadi_s6, (&w10), casadi_s7, (&w0), casadi_s4, w, 0);
  /* #340: @32 = vertcat(@31, @31, @23, @0, @30) */
  rr=w32;
  *rr++ = w23;
  *rr++ = w0;
  /* #341: @19 = @32[:2] */
  for (rr=w19, ss=w32+0; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #342: (@20[13:29:8] = @19) */
  for (rr=w20+13, ss=w19; rr!=w20+29; rr+=8) *rr = *ss++;
  /* #343: @23 = ones(10x1,1nz) */
  w23 = 1.;
  /* #344: {NULL, NULL, @0} = vertsplit(@23) */
  w0 = w23;
  /* #345: @23 = mac(@16,@0,@11) */
  casadi_copy((&w11), 1, (&w23));
  casadi_mtimes(w16, casadi_s6, (&w0), casadi_s8, (&w23), casadi_s4, w, 0);
  /* #346: @10 = mac(@18,@0,@11) */
  casadi_copy((&w11), 1, (&w10));
  casadi_mtimes(w18, casadi_s6, (&w0), casadi_s8, (&w10), casadi_s4, w, 0);
  /* #347: @19 = vertcat(@31, @31, @23, @10, @30) */
  rr=w19;
  *rr++ = w23;
  *rr++ = w10;
  /* #348: @32 = @19[:2] */
  for (rr=w32, ss=w19+0; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #349: (@20[14:30:8] = @32) */
  for (rr=w20+14, ss=w32; rr!=w20+30; rr+=8) *rr = *ss++;
  /* #350: @23 = ones(10x1,1nz) */
  w23 = 1.;
  /* #351: {NULL, NULL, @10} = vertsplit(@23) */
  w10 = w23;
  /* #352: @23 = mac(@16,@10,@11) */
  casadi_copy((&w11), 1, (&w23));
  casadi_mtimes(w16, casadi_s6, (&w10), casadi_s9, (&w23), casadi_s4, w, 0);
  /* #353: @11 = mac(@18,@10,@11) */
  casadi_mtimes(w18, casadi_s6, (&w10), casadi_s9, (&w11), casadi_s4, w, 0);
  /* #354: @32 = vertcat(@31, @31, @23, @11, @30) */
  rr=w32;
  *rr++ = w23;
  *rr++ = w11;
  /* #355: @19 = @32[:2] */
  for (rr=w19, ss=w32+0; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #356: (@20[15:31:8] = @19) */
  for (rr=w20+15, ss=w19; rr!=w20+31; rr+=8) *rr = *ss++;
  /* #357: output[1][0] = @20 */
  casadi_copy(w20, 26, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s12;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 84;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 84*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
