/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 4, 8, 16};
static const casadi_int casadi_s1[4] = {1, 5, 9, 17};
static const casadi_int casadi_s2[4] = {2, 6, 10, 18};
static const casadi_int casadi_s3[4] = {3, 7, 11, 19};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s6[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[4] = {0, 1, 0, 0};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s14[31] = {8, 4, 0, 4, 8, 16, 24, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};

/* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac:(i0[8],i1[0],i2[])->(o0[4],o1[8x4,24nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+19, *w16=w+23, *w17=w+27, *w18=w+31, *w19=w+35, w20, w21, w22, w23, w24, w25, *w26=w+65, *w28=w+69, *w29=w+71;
  /* #0: @0 = 0.125 */
  w0 = 1.2500000000000000e-01;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #21: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #22: @4 = (@0*@2) */
  w4  = (w0*w2);
  /* #23: @11 = (-@4) */
  w11 = (- w4 );
  /* #24: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #25: @12 = (@0*@5) */
  w12  = (w0*w5);
  /* #26: @11 = (@11-@12) */
  w11 -= w12;
  /* #27: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #28: @13 = (@0*@7) */
  w13  = (w0*w7);
  /* #29: @11 = (@11-@13) */
  w11 -= w13;
  /* #30: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #31: @14 = (@0*@9) */
  w14  = (w0*w9);
  /* #32: @11 = (@11-@14) */
  w11 -= w14;
  /* #33: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #34: @11 = 0 */
  w11 = 0.;
  /* #35: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #36: @15 = @1; (@15[3] += @14) */
  casadi_copy(w1, 4, w15);
  for (rr=w15+3, ss=(&w14); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #37: @14 = (@14+@13) */
  w14 += w13;
  /* #38: (@15[2] += @14) */
  for (rr=w15+2, ss=(&w14); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #39: @14 = (@14+@12) */
  w14 += w12;
  /* #40: (@15[1] += @14) */
  for (rr=w15+1, ss=(&w14); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #41: @14 = (@14+@4) */
  w14 += w4;
  /* #42: (@15[0] += @14) */
  for (rr=w15+0, ss=(&w14); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #43: @14 = @15[0] */
  for (rr=(&w14), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #44: @16 = @1; (@16[0] = @14) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+0, ss=(&w14); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #45: @14 = @15[1] */
  for (rr=(&w14), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #46: (@16[1] = @14) */
  for (rr=w16+1, ss=(&w14); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #47: @14 = @15[2] */
  for (rr=(&w14), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #48: (@16[2] = @14) */
  for (rr=w16+2, ss=(&w14); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #49: @14 = @15[3] */
  for (rr=(&w14), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #50: (@16[3] = @14) */
  for (rr=w16+3, ss=(&w14); rr!=w16+4; rr+=1) *rr = *ss++;
  /* #51: @16 = @16' */
  /* #52: @15 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 4, w15);
  /* #53: @14 = mac(@16,@15,@11) */
  casadi_copy((&w11), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #54: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #55: @14 = -0.125 */
  w14 = -1.2500000000000000e-01;
  /* #56: @4 = (@14*@10) */
  w4  = (w14*w10);
  /* #57: @12 = (-@4) */
  w12 = (- w4 );
  /* #58: @17 = @1; (@17[3] += @12) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w12); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #59: @12 = (@14*@8) */
  w12  = (w14*w8);
  /* #60: @12 = (-@12) */
  w12 = (- w12 );
  /* #61: @12 = (@12-@4) */
  w12 -= w4;
  /* #62: (@17[2] += @12) */
  for (rr=w17+2, ss=(&w12); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #63: @4 = (@14*@6) */
  w4  = (w14*w6);
  /* #64: @12 = (@12-@4) */
  w12 -= w4;
  /* #65: (@17[1] += @12) */
  for (rr=w17+1, ss=(&w12); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #66: @4 = (@14*@3) */
  w4  = (w14*w3);
  /* #67: @12 = (@12-@4) */
  w12 -= w4;
  /* #68: (@17[0] += @12) */
  for (rr=w17+0, ss=(&w12); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #69: @12 = @17[0] */
  for (rr=(&w12), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #70: @18 = @1; (@18[0] = @12) */
  casadi_copy(w1, 4, w18);
  for (rr=w18+0, ss=(&w12); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #71: @12 = @17[1] */
  for (rr=(&w12), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #72: (@18[1] = @12) */
  for (rr=w18+1, ss=(&w12); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #73: @12 = @17[2] */
  for (rr=(&w12), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #74: (@18[2] = @12) */
  for (rr=w18+2, ss=(&w12); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #75: @12 = @17[3] */
  for (rr=(&w12), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #76: (@18[3] = @12) */
  for (rr=w18+3, ss=(&w12); rr!=w18+4; rr+=1) *rr = *ss++;
  /* #77: @18 = @18' */
  /* #78: @12 = mac(@18,@15,@11) */
  casadi_copy((&w11), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #79: output[0][3] = @12 */
  if (res[0]) res[0][3] = w12;
  /* #80: @19 = zeros(8x4,24nz) */
  casadi_clear(w19, 24);
  /* #81: @12 = ones(8x1,1nz) */
  w12 = 1.;
  /* #82: {@4, NULL} = vertsplit(@12) */
  w4 = w12;
  /* #83: @12 = @4[0] */
  for (rr=(&w12), ss=(&w4)+0; ss!=(&w4)+1; ss+=1) *rr++ = *ss;
  /* #84: @2 = (@2*@12) */
  w2 *= w12;
  /* #85: @4 = (@0*@2) */
  w4  = (w0*w2);
  /* #86: @13 = (@5*@12) */
  w13  = (w5*w12);
  /* #87: @20 = (@0*@13) */
  w20  = (w0*w13);
  /* #88: @4 = (@4+@20) */
  w4 += w20;
  /* #89: @20 = (@7*@12) */
  w20  = (w7*w12);
  /* #90: @21 = (@0*@20) */
  w21  = (w0*w20);
  /* #91: @4 = (@4+@21) */
  w4 += w21;
  /* #92: @21 = (@9*@12) */
  w21  = (w9*w12);
  /* #93: @22 = (@0*@21) */
  w22  = (w0*w21);
  /* #94: @4 = (@4+@22) */
  w4 += w22;
  /* #95: @3 = (@3*@12) */
  w3 *= w12;
  /* #96: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #97: @22 = (@6*@12) */
  w22  = (w6*w12);
  /* #98: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #99: @23 = (@3+@22) */
  w23  = (w3+w22);
  /* #100: @24 = (@8*@12) */
  w24  = (w8*w12);
  /* #101: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #102: @23 = (@23+@24) */
  w23 += w24;
  /* #103: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #104: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #105: @23 = (@23+@12) */
  w23 += w12;
  /* #106: @25 = (-@12) */
  w25 = (- w12 );
  /* #107: @17 = @1; (@17[3] += @25) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w25); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #108: @24 = (-@24) */
  w24 = (- w24 );
  /* #109: @24 = (@24-@12) */
  w24 -= w12;
  /* #110: (@17[2] += @24) */
  for (rr=w17+2, ss=(&w24); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #111: @24 = (@24-@22) */
  w24 -= w22;
  /* #112: (@17[1] += @24) */
  for (rr=w17+1, ss=(&w24); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #113: @24 = (@24-@3) */
  w24 -= w3;
  /* #114: (@17[0] += @24) */
  for (rr=w17+0, ss=(&w24); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #115: @24 = @17[0] */
  for (rr=(&w24), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #116: @26 = @1; (@26[0] += @24) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+0, ss=(&w24); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #117: (@26[1] = @11) */
  for (rr=w26+1, ss=(&w11); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #118: @24 = @17[1] */
  for (rr=(&w24), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #119: (@26[1] += @24) */
  for (rr=w26+1, ss=(&w24); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #120: (@26[2] = @11) */
  for (rr=w26+2, ss=(&w11); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #121: @24 = @17[2] */
  for (rr=(&w24), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #122: (@26[2] += @24) */
  for (rr=w26+2, ss=(&w24); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #123: (@26[3] = @11) */
  for (rr=w26+3, ss=(&w11); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #124: @24 = @17[3] */
  for (rr=(&w24), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #125: (@26[3] += @24) */
  for (rr=w26+3, ss=(&w24); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #126: @26 = @26' */
  /* #127: @24 = mac(@26,@15,@11) */
  casadi_copy((&w11), 1, (&w24));
  for (i=0, rr=(&w24); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #128: @21 = (@14*@21) */
  w21  = (w14*w21);
  /* #129: @21 = (-@21) */
  w21 = (- w21 );
  /* #130: @26 = @1; (@26[3] += @21) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+3, ss=(&w21); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #131: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #132: @21 = (@21-@20) */
  w21 -= w20;
  /* #133: (@26[2] += @21) */
  for (rr=w26+2, ss=(&w21); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #134: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #135: @21 = (@21-@13) */
  w21 -= w13;
  /* #136: (@26[1] += @21) */
  for (rr=w26+1, ss=(&w21); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #137: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #138: @21 = (@21-@2) */
  w21 -= w2;
  /* #139: (@26[0] += @21) */
  for (rr=w26+0, ss=(&w21); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #140: @21 = @26[0] */
  for (rr=(&w21), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #141: @17 = @1; (@17[0] += @21) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w21); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #142: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #143: @21 = @26[1] */
  for (rr=(&w21), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #144: (@17[1] += @21) */
  for (rr=w17+1, ss=(&w21); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #145: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #146: @21 = @26[2] */
  for (rr=(&w21), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #147: (@17[2] += @21) */
  for (rr=w17+2, ss=(&w21); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #148: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #149: @21 = @26[3] */
  for (rr=(&w21), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #150: (@17[3] += @21) */
  for (rr=w17+3, ss=(&w21); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #151: @17 = @17' */
  /* #152: @21 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w21));
  for (i=0, rr=(&w21); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #153: @17 = vertcat(@4, @23, @24, @21) */
  rr=w17;
  *rr++ = w4;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w21;
  /* #154: (@19[0, 4, 8, 16] = @17) */
  for (cii=casadi_s0, rr=w19, ss=w17; cii!=casadi_s0+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #155: @4 = ones(8x1,1nz) */
  w4 = 1.;
  /* #156: {@23, NULL} = vertsplit(@4) */
  w23 = w4;
  /* #157: @4 = @23[0] */
  for (rr=(&w4), ss=(&w23)+0; ss!=(&w23)+1; ss+=1) *rr++ = *ss;
  /* #158: @5 = (@5*@4) */
  w5 *= w4;
  /* #159: @23 = (@0*@5) */
  w23  = (w0*w5);
  /* #160: @24 = (@7*@4) */
  w24  = (w7*w4);
  /* #161: @21 = (@0*@24) */
  w21  = (w0*w24);
  /* #162: @23 = (@23+@21) */
  w23 += w21;
  /* #163: @21 = (@9*@4) */
  w21  = (w9*w4);
  /* #164: @2 = (@0*@21) */
  w2  = (w0*w21);
  /* #165: @23 = (@23+@2) */
  w23 += w2;
  /* #166: @6 = (@6*@4) */
  w6 *= w4;
  /* #167: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #168: @2 = (@8*@4) */
  w2  = (w8*w4);
  /* #169: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #170: @13 = (@6+@2) */
  w13  = (w6+w2);
  /* #171: @4 = (@10*@4) */
  w4  = (w10*w4);
  /* #172: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #173: @13 = (@13+@4) */
  w13 += w4;
  /* #174: @20 = (-@4) */
  w20 = (- w4 );
  /* #175: @17 = @1; (@17[3] += @20) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w20); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #176: @2 = (-@2) */
  w2 = (- w2 );
  /* #177: @2 = (@2-@4) */
  w2 -= w4;
  /* #178: (@17[2] += @2) */
  for (rr=w17+2, ss=(&w2); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #179: @2 = (@2-@6) */
  w2 -= w6;
  /* #180: (@17[1] += @2) */
  for (rr=w17+1, ss=(&w2); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #181: (@17[0] += @2) */
  for (rr=w17+0, ss=(&w2); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #182: @2 = @17[0] */
  for (rr=(&w2), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #183: @26 = @1; (@26[0] += @2) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+0, ss=(&w2); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #184: (@26[1] = @11) */
  for (rr=w26+1, ss=(&w11); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #185: @2 = @17[1] */
  for (rr=(&w2), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #186: (@26[1] += @2) */
  for (rr=w26+1, ss=(&w2); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #187: (@26[2] = @11) */
  for (rr=w26+2, ss=(&w11); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #188: @2 = @17[2] */
  for (rr=(&w2), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #189: (@26[2] += @2) */
  for (rr=w26+2, ss=(&w2); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #190: (@26[3] = @11) */
  for (rr=w26+3, ss=(&w11); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #191: @2 = @17[3] */
  for (rr=(&w2), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #192: (@26[3] += @2) */
  for (rr=w26+3, ss=(&w2); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #193: @26 = @26' */
  /* #194: @2 = mac(@26,@15,@11) */
  casadi_copy((&w11), 1, (&w2));
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #195: @21 = (@14*@21) */
  w21  = (w14*w21);
  /* #196: @21 = (-@21) */
  w21 = (- w21 );
  /* #197: @26 = @1; (@26[3] += @21) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+3, ss=(&w21); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #198: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #199: @21 = (@21-@24) */
  w21 -= w24;
  /* #200: (@26[2] += @21) */
  for (rr=w26+2, ss=(&w21); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #201: @5 = (@14*@5) */
  w5  = (w14*w5);
  /* #202: @21 = (@21-@5) */
  w21 -= w5;
  /* #203: (@26[1] += @21) */
  for (rr=w26+1, ss=(&w21); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #204: (@26[0] += @21) */
  for (rr=w26+0, ss=(&w21); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #205: @21 = @26[0] */
  for (rr=(&w21), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #206: @17 = @1; (@17[0] += @21) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w21); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #207: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #208: @21 = @26[1] */
  for (rr=(&w21), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #209: (@17[1] += @21) */
  for (rr=w17+1, ss=(&w21); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #210: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #211: @21 = @26[2] */
  for (rr=(&w21), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #212: (@17[2] += @21) */
  for (rr=w17+2, ss=(&w21); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #213: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #214: @21 = @26[3] */
  for (rr=(&w21), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #215: (@17[3] += @21) */
  for (rr=w17+3, ss=(&w21); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #216: @17 = @17' */
  /* #217: @21 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w21));
  for (i=0, rr=(&w21); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #218: @17 = vertcat(@23, @13, @2, @21) */
  rr=w17;
  *rr++ = w23;
  *rr++ = w13;
  *rr++ = w2;
  *rr++ = w21;
  /* #219: (@19[1, 5, 9, 17] = @17) */
  for (cii=casadi_s1, rr=w19, ss=w17; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #220: @23 = ones(8x1,1nz) */
  w23 = 1.;
  /* #221: {@13, NULL} = vertsplit(@23) */
  w13 = w23;
  /* #222: @23 = @13[0] */
  for (rr=(&w23), ss=(&w13)+0; ss!=(&w13)+1; ss+=1) *rr++ = *ss;
  /* #223: @7 = (@7*@23) */
  w7 *= w23;
  /* #224: @13 = (@0*@7) */
  w13  = (w0*w7);
  /* #225: @2 = (@9*@23) */
  w2  = (w9*w23);
  /* #226: @21 = (@0*@2) */
  w21  = (w0*w2);
  /* #227: @13 = (@13+@21) */
  w13 += w21;
  /* #228: @8 = (@8*@23) */
  w8 *= w23;
  /* #229: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #230: @23 = (@10*@23) */
  w23  = (w10*w23);
  /* #231: @23 = (@0*@23) */
  w23  = (w0*w23);
  /* #232: @21 = (@8+@23) */
  w21  = (w8+w23);
  /* #233: @5 = (-@23) */
  w5 = (- w23 );
  /* #234: @17 = @1; (@17[3] += @5) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w5); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #235: @8 = (-@8) */
  w8 = (- w8 );
  /* #236: @8 = (@8-@23) */
  w8 -= w23;
  /* #237: (@17[2] += @8) */
  for (rr=w17+2, ss=(&w8); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #238: (@17[1] += @8) */
  for (rr=w17+1, ss=(&w8); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #239: (@17[0] += @8) */
  for (rr=w17+0, ss=(&w8); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #240: @8 = @17[0] */
  for (rr=(&w8), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #241: @26 = @1; (@26[0] += @8) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+0, ss=(&w8); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #242: (@26[1] = @11) */
  for (rr=w26+1, ss=(&w11); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #243: @8 = @17[1] */
  for (rr=(&w8), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #244: (@26[1] += @8) */
  for (rr=w26+1, ss=(&w8); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #245: (@26[2] = @11) */
  for (rr=w26+2, ss=(&w11); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #246: @8 = @17[2] */
  for (rr=(&w8), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #247: (@26[2] += @8) */
  for (rr=w26+2, ss=(&w8); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #248: (@26[3] = @11) */
  for (rr=w26+3, ss=(&w11); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #249: @8 = @17[3] */
  for (rr=(&w8), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #250: (@26[3] += @8) */
  for (rr=w26+3, ss=(&w8); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #251: @26 = @26' */
  /* #252: @8 = mac(@26,@15,@11) */
  casadi_copy((&w11), 1, (&w8));
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #253: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #254: @2 = (-@2) */
  w2 = (- w2 );
  /* #255: @26 = @1; (@26[3] += @2) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+3, ss=(&w2); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #256: @7 = (@14*@7) */
  w7  = (w14*w7);
  /* #257: @2 = (@2-@7) */
  w2 -= w7;
  /* #258: (@26[2] += @2) */
  for (rr=w26+2, ss=(&w2); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #259: (@26[1] += @2) */
  for (rr=w26+1, ss=(&w2); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #260: (@26[0] += @2) */
  for (rr=w26+0, ss=(&w2); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #261: @2 = @26[0] */
  for (rr=(&w2), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #262: @17 = @1; (@17[0] += @2) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+0, ss=(&w2); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #263: (@17[1] = @11) */
  for (rr=w17+1, ss=(&w11); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #264: @2 = @26[1] */
  for (rr=(&w2), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #265: (@17[1] += @2) */
  for (rr=w17+1, ss=(&w2); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #266: (@17[2] = @11) */
  for (rr=w17+2, ss=(&w11); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #267: @2 = @26[2] */
  for (rr=(&w2), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #268: (@17[2] += @2) */
  for (rr=w17+2, ss=(&w2); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #269: (@17[3] = @11) */
  for (rr=w17+3, ss=(&w11); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #270: @2 = @26[3] */
  for (rr=(&w2), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #271: (@17[3] += @2) */
  for (rr=w17+3, ss=(&w2); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #272: @17 = @17' */
  /* #273: @2 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w2));
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #274: @17 = vertcat(@13, @21, @8, @2) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w21;
  *rr++ = w8;
  *rr++ = w2;
  /* #275: (@19[2, 6, 10, 18] = @17) */
  for (cii=casadi_s2, rr=w19, ss=w17; cii!=casadi_s2+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #276: @13 = ones(8x1,1nz) */
  w13 = 1.;
  /* #277: {@21, NULL} = vertsplit(@13) */
  w21 = w13;
  /* #278: @13 = @21[0] */
  for (rr=(&w13), ss=(&w21)+0; ss!=(&w21)+1; ss+=1) *rr++ = *ss;
  /* #279: @9 = (@9*@13) */
  w9 *= w13;
  /* #280: @21 = (@0*@9) */
  w21  = (w0*w9);
  /* #281: @10 = (@10*@13) */
  w10 *= w13;
  /* #282: @0 = (@0*@10) */
  w0 *= w10;
  /* #283: @10 = (-@0) */
  w10 = (- w0 );
  /* #284: @17 = @1; (@17[3] += @10) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w10); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #285: (@17[2] += @10) */
  for (rr=w17+2, ss=(&w10); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #286: (@17[1] += @10) */
  for (rr=w17+1, ss=(&w10); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #287: (@17[0] += @10) */
  for (rr=w17+0, ss=(&w10); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #288: @10 = @17[0] */
  for (rr=(&w10), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #289: @26 = @1; (@26[0] += @10) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+0, ss=(&w10); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #290: (@26[1] = @11) */
  for (rr=w26+1, ss=(&w11); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #291: @10 = @17[1] */
  for (rr=(&w10), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #292: (@26[1] += @10) */
  for (rr=w26+1, ss=(&w10); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #293: (@26[2] = @11) */
  for (rr=w26+2, ss=(&w11); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #294: @10 = @17[2] */
  for (rr=(&w10), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #295: (@26[2] += @10) */
  for (rr=w26+2, ss=(&w10); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #296: (@26[3] = @11) */
  for (rr=w26+3, ss=(&w11); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #297: @10 = @17[3] */
  for (rr=(&w10), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #298: (@26[3] += @10) */
  for (rr=w26+3, ss=(&w10); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #299: @26 = @26' */
  /* #300: @10 = mac(@26,@15,@11) */
  casadi_copy((&w11), 1, (&w10));
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #301: @14 = (@14*@9) */
  w14 *= w9;
  /* #302: @14 = (-@14) */
  w14 = (- w14 );
  /* #303: @26 = @1; (@26[3] += @14) */
  casadi_copy(w1, 4, w26);
  for (rr=w26+3, ss=(&w14); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #304: (@26[2] += @14) */
  for (rr=w26+2, ss=(&w14); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #305: (@26[1] += @14) */
  for (rr=w26+1, ss=(&w14); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #306: (@26[0] += @14) */
  for (rr=w26+0, ss=(&w14); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #307: @14 = @26[0] */
  for (rr=(&w14), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #308: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #309: (@1[1] = @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #310: @14 = @26[1] */
  for (rr=(&w14), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #311: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #312: (@1[2] = @11) */
  for (rr=w1+2, ss=(&w11); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #313: @14 = @26[2] */
  for (rr=(&w14), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #314: (@1[2] += @14) */
  for (rr=w1+2, ss=(&w14); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #315: (@1[3] = @11) */
  for (rr=w1+3, ss=(&w11); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #316: @14 = @26[3] */
  for (rr=(&w14), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #317: (@1[3] += @14) */
  for (rr=w1+3, ss=(&w14); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #318: @1 = @1' */
  /* #319: @14 = mac(@1,@15,@11) */
  casadi_copy((&w11), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #320: @1 = vertcat(@21, @0, @10, @14) */
  rr=w1;
  *rr++ = w21;
  *rr++ = w0;
  *rr++ = w10;
  *rr++ = w14;
  /* #321: (@19[3, 7, 11, 19] = @1) */
  for (cii=casadi_s3, rr=w19, ss=w1; cii!=casadi_s3+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #322: @27 = 00 */
  /* #323: @21 = ones(8x1,1nz) */
  w21 = 1.;
  /* #324: {NULL, @0} = vertsplit(@21) */
  w0 = w21;
  /* #325: @21 = mac(@16,@0,@11) */
  casadi_copy((&w11), 1, (&w21));
  casadi_mtimes(w16, casadi_s6, (&w0), casadi_s5, (&w21), casadi_s4, w, 0);
  /* #326: @10 = mac(@18,@0,@11) */
  casadi_copy((&w11), 1, (&w10));
  casadi_mtimes(w18, casadi_s6, (&w0), casadi_s5, (&w10), casadi_s4, w, 0);
  /* #327: @28 = vertcat(@27, @27, @21, @10) */
  rr=w28;
  *rr++ = w21;
  *rr++ = w10;
  /* #328: @29 = @28[:2] */
  for (rr=w29, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #329: (@19[12:28:8] = @29) */
  for (rr=w19+12, ss=w29; rr!=w19+28; rr+=8) *rr = *ss++;
  /* #330: @21 = ones(8x1,1nz) */
  w21 = 1.;
  /* #331: {NULL, @10} = vertsplit(@21) */
  w10 = w21;
  /* #332: @21 = mac(@16,@10,@11) */
  casadi_copy((&w11), 1, (&w21));
  casadi_mtimes(w16, casadi_s6, (&w10), casadi_s7, (&w21), casadi_s4, w, 0);
  /* #333: @0 = mac(@18,@10,@11) */
  casadi_copy((&w11), 1, (&w0));
  casadi_mtimes(w18, casadi_s6, (&w10), casadi_s7, (&w0), casadi_s4, w, 0);
  /* #334: @29 = vertcat(@27, @27, @21, @0) */
  rr=w29;
  *rr++ = w21;
  *rr++ = w0;
  /* #335: @28 = @29[:2] */
  for (rr=w28, ss=w29+0; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #336: (@19[13:29:8] = @28) */
  for (rr=w19+13, ss=w28; rr!=w19+29; rr+=8) *rr = *ss++;
  /* #337: @21 = ones(8x1,1nz) */
  w21 = 1.;
  /* #338: {NULL, @0} = vertsplit(@21) */
  w0 = w21;
  /* #339: @21 = mac(@16,@0,@11) */
  casadi_copy((&w11), 1, (&w21));
  casadi_mtimes(w16, casadi_s6, (&w0), casadi_s8, (&w21), casadi_s4, w, 0);
  /* #340: @10 = mac(@18,@0,@11) */
  casadi_copy((&w11), 1, (&w10));
  casadi_mtimes(w18, casadi_s6, (&w0), casadi_s8, (&w10), casadi_s4, w, 0);
  /* #341: @28 = vertcat(@27, @27, @21, @10) */
  rr=w28;
  *rr++ = w21;
  *rr++ = w10;
  /* #342: @29 = @28[:2] */
  for (rr=w29, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #343: (@19[14:30:8] = @29) */
  for (rr=w19+14, ss=w29; rr!=w19+30; rr+=8) *rr = *ss++;
  /* #344: @21 = ones(8x1,1nz) */
  w21 = 1.;
  /* #345: {NULL, @10} = vertsplit(@21) */
  w10 = w21;
  /* #346: @21 = mac(@16,@10,@11) */
  casadi_copy((&w11), 1, (&w21));
  casadi_mtimes(w16, casadi_s6, (&w10), casadi_s9, (&w21), casadi_s4, w, 0);
  /* #347: @11 = mac(@18,@10,@11) */
  casadi_mtimes(w18, casadi_s6, (&w10), casadi_s9, (&w11), casadi_s4, w, 0);
  /* #348: @29 = vertcat(@27, @27, @21, @11) */
  rr=w29;
  *rr++ = w21;
  *rr++ = w11;
  /* #349: @28 = @29[:2] */
  for (rr=w28, ss=w29+0; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #350: (@19[15:31:8] = @28) */
  for (rr=w19+15, ss=w28; rr!=w19+31; rr+=8) *rr = *ss++;
  /* #351: output[1][0] = @19 */
  casadi_copy(w19, 24, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 73;
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 73*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
