/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 4, 8, 16};
static const casadi_int casadi_s1[4] = {1, 5, 9, 17};
static const casadi_int casadi_s2[4] = {2, 6, 10, 18};
static const casadi_int casadi_s3[4] = {3, 7, 11, 19};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s6[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[8] = {0, 8, 16, 24, 32, 36, 40, 44};
static const casadi_int casadi_s11[8] = {1, 9, 17, 25, 33, 37, 41, 45};
static const casadi_int casadi_s12[8] = {2, 10, 18, 26, 34, 38, 42, 46};
static const casadi_int casadi_s13[8] = {3, 11, 19, 27, 35, 39, 43, 47};
static const casadi_int casadi_s14[59] = {8, 8, 0, 8, 16, 24, 32, 36, 40, 44, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s15[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s16[4] = {0, 1, 0, 0};
static const casadi_int casadi_s17[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s18[3] = {0, 0, 0};
static const casadi_int casadi_s19[31] = {8, 4, 0, 4, 8, 16, 24, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};

/* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess:(i0[8],i1[0],i2[4],i3[])->(o0[4],o1[8x4,24nz],o2[8x8,48nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+19, *w16=w+23, *w17=w+27, *w18=w+31, *w19=w+35, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+71, *w33=w+75, w34, w35, w36, w37, w38, *w39=w+84, *w40=w+88, w41, w42, w43, *w44=w+95, *w45=w+99, *w46=w+103, w47, *w48=w+108, *w50=w+112, *w51=w+114, w52, w53, *w54=w+118, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, *w66=w+177, *w67=w+185;
  /* #0: @0 = 0.125 */
  w0 = 1.2500000000000000e-01;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #21: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #22: @4 = (@0*@2) */
  w4  = (w0*w2);
  /* #23: @11 = (-@4) */
  w11 = (- w4 );
  /* #24: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #25: @12 = (@0*@5) */
  w12  = (w0*w5);
  /* #26: @11 = (@11-@12) */
  w11 -= w12;
  /* #27: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #28: @13 = (@0*@7) */
  w13  = (w0*w7);
  /* #29: @11 = (@11-@13) */
  w11 -= w13;
  /* #30: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #31: @14 = (@0*@9) */
  w14  = (w0*w9);
  /* #32: @11 = (@11-@14) */
  w11 -= w14;
  /* #33: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #34: @11 = 0 */
  w11 = 0.;
  /* #35: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #36: @15 = @1; (@15[3] += @14) */
  casadi_copy(w1, 4, w15);
  for (rr=w15+3, ss=(&w14); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #37: @14 = (@14+@13) */
  w14 += w13;
  /* #38: (@15[2] += @14) */
  for (rr=w15+2, ss=(&w14); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #39: @14 = (@14+@12) */
  w14 += w12;
  /* #40: (@15[1] += @14) */
  for (rr=w15+1, ss=(&w14); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #41: @14 = (@14+@4) */
  w14 += w4;
  /* #42: (@15[0] += @14) */
  for (rr=w15+0, ss=(&w14); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #43: @14 = @15[0] */
  for (rr=(&w14), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #44: @16 = @1; (@16[0] = @14) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+0, ss=(&w14); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #45: @14 = @15[1] */
  for (rr=(&w14), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #46: (@16[1] = @14) */
  for (rr=w16+1, ss=(&w14); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #47: @14 = @15[2] */
  for (rr=(&w14), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #48: (@16[2] = @14) */
  for (rr=w16+2, ss=(&w14); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #49: @14 = @15[3] */
  for (rr=(&w14), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #50: (@16[3] = @14) */
  for (rr=w16+3, ss=(&w14); rr!=w16+4; rr+=1) *rr = *ss++;
  /* #51: @16 = @16' */
  /* #52: @15 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+4 : 0, 4, w15);
  /* #53: @14 = mac(@16,@15,@11) */
  casadi_copy((&w11), 1, (&w14));
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #54: output[0][2] = @14 */
  if (res[0]) res[0][2] = w14;
  /* #55: @14 = -0.125 */
  w14 = -1.2500000000000000e-01;
  /* #56: @4 = (@14*@10) */
  w4  = (w14*w10);
  /* #57: @12 = (-@4) */
  w12 = (- w4 );
  /* #58: @17 = @1; (@17[3] += @12) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w12); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #59: @12 = (@14*@8) */
  w12  = (w14*w8);
  /* #60: @12 = (-@12) */
  w12 = (- w12 );
  /* #61: @12 = (@12-@4) */
  w12 -= w4;
  /* #62: (@17[2] += @12) */
  for (rr=w17+2, ss=(&w12); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #63: @4 = (@14*@6) */
  w4  = (w14*w6);
  /* #64: @12 = (@12-@4) */
  w12 -= w4;
  /* #65: (@17[1] += @12) */
  for (rr=w17+1, ss=(&w12); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #66: @4 = (@14*@3) */
  w4  = (w14*w3);
  /* #67: @12 = (@12-@4) */
  w12 -= w4;
  /* #68: (@17[0] += @12) */
  for (rr=w17+0, ss=(&w12); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #69: @12 = @17[0] */
  for (rr=(&w12), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #70: @18 = @1; (@18[0] = @12) */
  casadi_copy(w1, 4, w18);
  for (rr=w18+0, ss=(&w12); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #71: @12 = @17[1] */
  for (rr=(&w12), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #72: (@18[1] = @12) */
  for (rr=w18+1, ss=(&w12); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #73: @12 = @17[2] */
  for (rr=(&w12), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #74: (@18[2] = @12) */
  for (rr=w18+2, ss=(&w12); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #75: @12 = @17[3] */
  for (rr=(&w12), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #76: (@18[3] = @12) */
  for (rr=w18+3, ss=(&w12); rr!=w18+4; rr+=1) *rr = *ss++;
  /* #77: @18 = @18' */
  /* #78: @12 = mac(@18,@15,@11) */
  casadi_copy((&w11), 1, (&w12));
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #79: output[0][3] = @12 */
  if (res[0]) res[0][3] = w12;
  /* #80: @19 = zeros(8x4,24nz) */
  casadi_clear(w19, 24);
  /* #81: @12 = ones(8x1,1nz) */
  w12 = 1.;
  /* #82: {@4, NULL} = vertsplit(@12) */
  w4 = w12;
  /* #83: @12 = @4[0] */
  for (rr=(&w12), ss=(&w4)+0; ss!=(&w4)+1; ss+=1) *rr++ = *ss;
  /* #84: @4 = (@2*@12) */
  w4  = (w2*w12);
  /* #85: @13 = (@0*@4) */
  w13  = (w0*w4);
  /* #86: @20 = (@5*@12) */
  w20  = (w5*w12);
  /* #87: @21 = (@0*@20) */
  w21  = (w0*w20);
  /* #88: @13 = (@13+@21) */
  w13 += w21;
  /* #89: @21 = (@7*@12) */
  w21  = (w7*w12);
  /* #90: @22 = (@0*@21) */
  w22  = (w0*w21);
  /* #91: @13 = (@13+@22) */
  w13 += w22;
  /* #92: @22 = (@9*@12) */
  w22  = (w9*w12);
  /* #93: @23 = (@0*@22) */
  w23  = (w0*w22);
  /* #94: @13 = (@13+@23) */
  w13 += w23;
  /* #95: @23 = (@3*@12) */
  w23  = (w3*w12);
  /* #96: @24 = (@0*@23) */
  w24  = (w0*w23);
  /* #97: @25 = (@6*@12) */
  w25  = (w6*w12);
  /* #98: @26 = (@0*@25) */
  w26  = (w0*w25);
  /* #99: @27 = (@24+@26) */
  w27  = (w24+w26);
  /* #100: @28 = (@8*@12) */
  w28  = (w8*w12);
  /* #101: @29 = (@0*@28) */
  w29  = (w0*w28);
  /* #102: @27 = (@27+@29) */
  w27 += w29;
  /* #103: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #104: @30 = (@0*@12) */
  w30  = (w0*w12);
  /* #105: @27 = (@27+@30) */
  w27 += w30;
  /* #106: @31 = (-@30) */
  w31 = (- w30 );
  /* #107: @17 = @1; (@17[3] += @31) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w31); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #108: @29 = (-@29) */
  w29 = (- w29 );
  /* #109: @29 = (@29-@30) */
  w29 -= w30;
  /* #110: (@17[2] += @29) */
  for (rr=w17+2, ss=(&w29); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #111: @29 = (@29-@26) */
  w29 -= w26;
  /* #112: (@17[1] += @29) */
  for (rr=w17+1, ss=(&w29); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #113: @29 = (@29-@24) */
  w29 -= w24;
  /* #114: (@17[0] += @29) */
  for (rr=w17+0, ss=(&w29); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #115: @29 = @17[0] */
  for (rr=(&w29), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #116: @32 = @1; (@32[0] += @29) */
  casadi_copy(w1, 4, w32);
  for (rr=w32+0, ss=(&w29); rr!=w32+1; rr+=1) *rr += *ss++;
  /* #117: (@32[1] = @11) */
  for (rr=w32+1, ss=(&w11); rr!=w32+2; rr+=1) *rr = *ss++;
  /* #118: @29 = @17[1] */
  for (rr=(&w29), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #119: (@32[1] += @29) */
  for (rr=w32+1, ss=(&w29); rr!=w32+2; rr+=1) *rr += *ss++;
  /* #120: (@32[2] = @11) */
  for (rr=w32+2, ss=(&w11); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #121: @29 = @17[2] */
  for (rr=(&w29), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #122: (@32[2] += @29) */
  for (rr=w32+2, ss=(&w29); rr!=w32+3; rr+=1) *rr += *ss++;
  /* #123: (@32[3] = @11) */
  for (rr=w32+3, ss=(&w11); rr!=w32+4; rr+=1) *rr = *ss++;
  /* #124: @29 = @17[3] */
  for (rr=(&w29), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #125: (@32[3] += @29) */
  for (rr=w32+3, ss=(&w29); rr!=w32+4; rr+=1) *rr += *ss++;
  /* #126: @17 = @32' */
  casadi_copy(w32, 4, w17);
  /* #127: @29 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w29));
  for (i=0, rr=(&w29); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #128: @24 = (@14*@22) */
  w24  = (w14*w22);
  /* #129: @24 = (-@24) */
  w24 = (- w24 );
  /* #130: @17 = @1; (@17[3] += @24) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w24); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #131: @26 = (@14*@21) */
  w26  = (w14*w21);
  /* #132: @24 = (@24-@26) */
  w24 -= w26;
  /* #133: (@17[2] += @24) */
  for (rr=w17+2, ss=(&w24); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #134: @26 = (@14*@20) */
  w26  = (w14*w20);
  /* #135: @24 = (@24-@26) */
  w24 -= w26;
  /* #136: (@17[1] += @24) */
  for (rr=w17+1, ss=(&w24); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #137: @26 = (@14*@4) */
  w26  = (w14*w4);
  /* #138: @24 = (@24-@26) */
  w24 -= w26;
  /* #139: (@17[0] += @24) */
  for (rr=w17+0, ss=(&w24); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #140: @24 = @17[0] */
  for (rr=(&w24), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #141: @33 = @1; (@33[0] += @24) */
  casadi_copy(w1, 4, w33);
  for (rr=w33+0, ss=(&w24); rr!=w33+1; rr+=1) *rr += *ss++;
  /* #142: (@33[1] = @11) */
  for (rr=w33+1, ss=(&w11); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #143: @24 = @17[1] */
  for (rr=(&w24), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #144: (@33[1] += @24) */
  for (rr=w33+1, ss=(&w24); rr!=w33+2; rr+=1) *rr += *ss++;
  /* #145: (@33[2] = @11) */
  for (rr=w33+2, ss=(&w11); rr!=w33+3; rr+=1) *rr = *ss++;
  /* #146: @24 = @17[2] */
  for (rr=(&w24), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #147: (@33[2] += @24) */
  for (rr=w33+2, ss=(&w24); rr!=w33+3; rr+=1) *rr += *ss++;
  /* #148: (@33[3] = @11) */
  for (rr=w33+3, ss=(&w11); rr!=w33+4; rr+=1) *rr = *ss++;
  /* #149: @24 = @17[3] */
  for (rr=(&w24), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #150: (@33[3] += @24) */
  for (rr=w33+3, ss=(&w24); rr!=w33+4; rr+=1) *rr += *ss++;
  /* #151: @17 = @33' */
  casadi_copy(w33, 4, w17);
  /* #152: @24 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w24));
  for (i=0, rr=(&w24); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #153: @17 = vertcat(@13, @27, @29, @24) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w27;
  *rr++ = w29;
  *rr++ = w24;
  /* #154: (@19[0, 4, 8, 16] = @17) */
  for (cii=casadi_s0, rr=w19, ss=w17; cii!=casadi_s0+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #155: @13 = ones(8x1,1nz) */
  w13 = 1.;
  /* #156: {@27, NULL} = vertsplit(@13) */
  w27 = w13;
  /* #157: @13 = @27[0] */
  for (rr=(&w13), ss=(&w27)+0; ss!=(&w27)+1; ss+=1) *rr++ = *ss;
  /* #158: @27 = (@5*@13) */
  w27  = (w5*w13);
  /* #159: @29 = (@0*@27) */
  w29  = (w0*w27);
  /* #160: @24 = (@7*@13) */
  w24  = (w7*w13);
  /* #161: @26 = (@0*@24) */
  w26  = (w0*w24);
  /* #162: @29 = (@29+@26) */
  w29 += w26;
  /* #163: @26 = (@9*@13) */
  w26  = (w9*w13);
  /* #164: @30 = (@0*@26) */
  w30  = (w0*w26);
  /* #165: @29 = (@29+@30) */
  w29 += w30;
  /* #166: @30 = (@6*@13) */
  w30  = (w6*w13);
  /* #167: @31 = (@0*@30) */
  w31  = (w0*w30);
  /* #168: @34 = (@8*@13) */
  w34  = (w8*w13);
  /* #169: @35 = (@0*@34) */
  w35  = (w0*w34);
  /* #170: @36 = (@31+@35) */
  w36  = (w31+w35);
  /* #171: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #172: @37 = (@0*@13) */
  w37  = (w0*w13);
  /* #173: @36 = (@36+@37) */
  w36 += w37;
  /* #174: @38 = (-@37) */
  w38 = (- w37 );
  /* #175: @17 = @1; (@17[3] += @38) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w38); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #176: @35 = (-@35) */
  w35 = (- w35 );
  /* #177: @35 = (@35-@37) */
  w35 -= w37;
  /* #178: (@17[2] += @35) */
  for (rr=w17+2, ss=(&w35); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #179: @35 = (@35-@31) */
  w35 -= w31;
  /* #180: (@17[1] += @35) */
  for (rr=w17+1, ss=(&w35); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #181: (@17[0] += @35) */
  for (rr=w17+0, ss=(&w35); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #182: @35 = @17[0] */
  for (rr=(&w35), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #183: @39 = @1; (@39[0] += @35) */
  casadi_copy(w1, 4, w39);
  for (rr=w39+0, ss=(&w35); rr!=w39+1; rr+=1) *rr += *ss++;
  /* #184: (@39[1] = @11) */
  for (rr=w39+1, ss=(&w11); rr!=w39+2; rr+=1) *rr = *ss++;
  /* #185: @35 = @17[1] */
  for (rr=(&w35), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #186: (@39[1] += @35) */
  for (rr=w39+1, ss=(&w35); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #187: (@39[2] = @11) */
  for (rr=w39+2, ss=(&w11); rr!=w39+3; rr+=1) *rr = *ss++;
  /* #188: @35 = @17[2] */
  for (rr=(&w35), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #189: (@39[2] += @35) */
  for (rr=w39+2, ss=(&w35); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #190: (@39[3] = @11) */
  for (rr=w39+3, ss=(&w11); rr!=w39+4; rr+=1) *rr = *ss++;
  /* #191: @35 = @17[3] */
  for (rr=(&w35), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #192: (@39[3] += @35) */
  for (rr=w39+3, ss=(&w35); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #193: @17 = @39' */
  casadi_copy(w39, 4, w17);
  /* #194: @35 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w35));
  for (i=0, rr=(&w35); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #195: @31 = (@14*@26) */
  w31  = (w14*w26);
  /* #196: @31 = (-@31) */
  w31 = (- w31 );
  /* #197: @17 = @1; (@17[3] += @31) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w31); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #198: @37 = (@14*@24) */
  w37  = (w14*w24);
  /* #199: @31 = (@31-@37) */
  w31 -= w37;
  /* #200: (@17[2] += @31) */
  for (rr=w17+2, ss=(&w31); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #201: @37 = (@14*@27) */
  w37  = (w14*w27);
  /* #202: @31 = (@31-@37) */
  w31 -= w37;
  /* #203: (@17[1] += @31) */
  for (rr=w17+1, ss=(&w31); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #204: (@17[0] += @31) */
  for (rr=w17+0, ss=(&w31); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #205: @31 = @17[0] */
  for (rr=(&w31), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #206: @40 = @1; (@40[0] += @31) */
  casadi_copy(w1, 4, w40);
  for (rr=w40+0, ss=(&w31); rr!=w40+1; rr+=1) *rr += *ss++;
  /* #207: (@40[1] = @11) */
  for (rr=w40+1, ss=(&w11); rr!=w40+2; rr+=1) *rr = *ss++;
  /* #208: @31 = @17[1] */
  for (rr=(&w31), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #209: (@40[1] += @31) */
  for (rr=w40+1, ss=(&w31); rr!=w40+2; rr+=1) *rr += *ss++;
  /* #210: (@40[2] = @11) */
  for (rr=w40+2, ss=(&w11); rr!=w40+3; rr+=1) *rr = *ss++;
  /* #211: @31 = @17[2] */
  for (rr=(&w31), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #212: (@40[2] += @31) */
  for (rr=w40+2, ss=(&w31); rr!=w40+3; rr+=1) *rr += *ss++;
  /* #213: (@40[3] = @11) */
  for (rr=w40+3, ss=(&w11); rr!=w40+4; rr+=1) *rr = *ss++;
  /* #214: @31 = @17[3] */
  for (rr=(&w31), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #215: (@40[3] += @31) */
  for (rr=w40+3, ss=(&w31); rr!=w40+4; rr+=1) *rr += *ss++;
  /* #216: @17 = @40' */
  casadi_copy(w40, 4, w17);
  /* #217: @31 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w31));
  for (i=0, rr=(&w31); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #218: @17 = vertcat(@29, @36, @35, @31) */
  rr=w17;
  *rr++ = w29;
  *rr++ = w36;
  *rr++ = w35;
  *rr++ = w31;
  /* #219: (@19[1, 5, 9, 17] = @17) */
  for (cii=casadi_s1, rr=w19, ss=w17; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #220: @29 = ones(8x1,1nz) */
  w29 = 1.;
  /* #221: {@36, NULL} = vertsplit(@29) */
  w36 = w29;
  /* #222: @29 = @36[0] */
  for (rr=(&w29), ss=(&w36)+0; ss!=(&w36)+1; ss+=1) *rr++ = *ss;
  /* #223: @36 = (@7*@29) */
  w36  = (w7*w29);
  /* #224: @35 = (@0*@36) */
  w35  = (w0*w36);
  /* #225: @31 = (@9*@29) */
  w31  = (w9*w29);
  /* #226: @37 = (@0*@31) */
  w37  = (w0*w31);
  /* #227: @35 = (@35+@37) */
  w35 += w37;
  /* #228: @37 = (@8*@29) */
  w37  = (w8*w29);
  /* #229: @38 = (@0*@37) */
  w38  = (w0*w37);
  /* #230: @29 = (@10*@29) */
  w29  = (w10*w29);
  /* #231: @41 = (@0*@29) */
  w41  = (w0*w29);
  /* #232: @42 = (@38+@41) */
  w42  = (w38+w41);
  /* #233: @43 = (-@41) */
  w43 = (- w41 );
  /* #234: @17 = @1; (@17[3] += @43) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w43); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #235: @38 = (-@38) */
  w38 = (- w38 );
  /* #236: @38 = (@38-@41) */
  w38 -= w41;
  /* #237: (@17[2] += @38) */
  for (rr=w17+2, ss=(&w38); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #238: (@17[1] += @38) */
  for (rr=w17+1, ss=(&w38); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #239: (@17[0] += @38) */
  for (rr=w17+0, ss=(&w38); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #240: @38 = @17[0] */
  for (rr=(&w38), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #241: @44 = @1; (@44[0] += @38) */
  casadi_copy(w1, 4, w44);
  for (rr=w44+0, ss=(&w38); rr!=w44+1; rr+=1) *rr += *ss++;
  /* #242: (@44[1] = @11) */
  for (rr=w44+1, ss=(&w11); rr!=w44+2; rr+=1) *rr = *ss++;
  /* #243: @38 = @17[1] */
  for (rr=(&w38), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #244: (@44[1] += @38) */
  for (rr=w44+1, ss=(&w38); rr!=w44+2; rr+=1) *rr += *ss++;
  /* #245: (@44[2] = @11) */
  for (rr=w44+2, ss=(&w11); rr!=w44+3; rr+=1) *rr = *ss++;
  /* #246: @38 = @17[2] */
  for (rr=(&w38), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #247: (@44[2] += @38) */
  for (rr=w44+2, ss=(&w38); rr!=w44+3; rr+=1) *rr += *ss++;
  /* #248: (@44[3] = @11) */
  for (rr=w44+3, ss=(&w11); rr!=w44+4; rr+=1) *rr = *ss++;
  /* #249: @38 = @17[3] */
  for (rr=(&w38), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #250: (@44[3] += @38) */
  for (rr=w44+3, ss=(&w38); rr!=w44+4; rr+=1) *rr += *ss++;
  /* #251: @17 = @44' */
  casadi_copy(w44, 4, w17);
  /* #252: @38 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w38));
  for (i=0, rr=(&w38); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #253: @41 = (@14*@31) */
  w41  = (w14*w31);
  /* #254: @41 = (-@41) */
  w41 = (- w41 );
  /* #255: @17 = @1; (@17[3] += @41) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w41); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #256: @43 = (@14*@36) */
  w43  = (w14*w36);
  /* #257: @41 = (@41-@43) */
  w41 -= w43;
  /* #258: (@17[2] += @41) */
  for (rr=w17+2, ss=(&w41); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #259: (@17[1] += @41) */
  for (rr=w17+1, ss=(&w41); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #260: (@17[0] += @41) */
  for (rr=w17+0, ss=(&w41); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #261: @41 = @17[0] */
  for (rr=(&w41), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #262: @45 = @1; (@45[0] += @41) */
  casadi_copy(w1, 4, w45);
  for (rr=w45+0, ss=(&w41); rr!=w45+1; rr+=1) *rr += *ss++;
  /* #263: (@45[1] = @11) */
  for (rr=w45+1, ss=(&w11); rr!=w45+2; rr+=1) *rr = *ss++;
  /* #264: @41 = @17[1] */
  for (rr=(&w41), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #265: (@45[1] += @41) */
  for (rr=w45+1, ss=(&w41); rr!=w45+2; rr+=1) *rr += *ss++;
  /* #266: (@45[2] = @11) */
  for (rr=w45+2, ss=(&w11); rr!=w45+3; rr+=1) *rr = *ss++;
  /* #267: @41 = @17[2] */
  for (rr=(&w41), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #268: (@45[2] += @41) */
  for (rr=w45+2, ss=(&w41); rr!=w45+3; rr+=1) *rr += *ss++;
  /* #269: (@45[3] = @11) */
  for (rr=w45+3, ss=(&w11); rr!=w45+4; rr+=1) *rr = *ss++;
  /* #270: @41 = @17[3] */
  for (rr=(&w41), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #271: (@45[3] += @41) */
  for (rr=w45+3, ss=(&w41); rr!=w45+4; rr+=1) *rr += *ss++;
  /* #272: @17 = @45' */
  casadi_copy(w45, 4, w17);
  /* #273: @41 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w41));
  for (i=0, rr=(&w41); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #274: @17 = vertcat(@35, @42, @38, @41) */
  rr=w17;
  *rr++ = w35;
  *rr++ = w42;
  *rr++ = w38;
  *rr++ = w41;
  /* #275: (@19[2, 6, 10, 18] = @17) */
  for (cii=casadi_s2, rr=w19, ss=w17; cii!=casadi_s2+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #276: @35 = ones(8x1,1nz) */
  w35 = 1.;
  /* #277: {@42, NULL} = vertsplit(@35) */
  w42 = w35;
  /* #278: @35 = @42[0] */
  for (rr=(&w35), ss=(&w42)+0; ss!=(&w42)+1; ss+=1) *rr++ = *ss;
  /* #279: @42 = (@9*@35) */
  w42  = (w9*w35);
  /* #280: @38 = (@0*@42) */
  w38  = (w0*w42);
  /* #281: @35 = (@10*@35) */
  w35  = (w10*w35);
  /* #282: @41 = (@0*@35) */
  w41  = (w0*w35);
  /* #283: @43 = (-@41) */
  w43 = (- w41 );
  /* #284: @17 = @1; (@17[3] += @43) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w43); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #285: (@17[2] += @43) */
  for (rr=w17+2, ss=(&w43); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #286: (@17[1] += @43) */
  for (rr=w17+1, ss=(&w43); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #287: (@17[0] += @43) */
  for (rr=w17+0, ss=(&w43); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #288: @43 = @17[0] */
  for (rr=(&w43), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #289: @46 = @1; (@46[0] += @43) */
  casadi_copy(w1, 4, w46);
  for (rr=w46+0, ss=(&w43); rr!=w46+1; rr+=1) *rr += *ss++;
  /* #290: (@46[1] = @11) */
  for (rr=w46+1, ss=(&w11); rr!=w46+2; rr+=1) *rr = *ss++;
  /* #291: @43 = @17[1] */
  for (rr=(&w43), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #292: (@46[1] += @43) */
  for (rr=w46+1, ss=(&w43); rr!=w46+2; rr+=1) *rr += *ss++;
  /* #293: (@46[2] = @11) */
  for (rr=w46+2, ss=(&w11); rr!=w46+3; rr+=1) *rr = *ss++;
  /* #294: @43 = @17[2] */
  for (rr=(&w43), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #295: (@46[2] += @43) */
  for (rr=w46+2, ss=(&w43); rr!=w46+3; rr+=1) *rr += *ss++;
  /* #296: (@46[3] = @11) */
  for (rr=w46+3, ss=(&w11); rr!=w46+4; rr+=1) *rr = *ss++;
  /* #297: @43 = @17[3] */
  for (rr=(&w43), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #298: (@46[3] += @43) */
  for (rr=w46+3, ss=(&w43); rr!=w46+4; rr+=1) *rr += *ss++;
  /* #299: @17 = @46' */
  casadi_copy(w46, 4, w17);
  /* #300: @43 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w43));
  for (i=0, rr=(&w43); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #301: @47 = (@14*@42) */
  w47  = (w14*w42);
  /* #302: @47 = (-@47) */
  w47 = (- w47 );
  /* #303: @17 = @1; (@17[3] += @47) */
  casadi_copy(w1, 4, w17);
  for (rr=w17+3, ss=(&w47); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #304: (@17[2] += @47) */
  for (rr=w17+2, ss=(&w47); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #305: (@17[1] += @47) */
  for (rr=w17+1, ss=(&w47); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #306: (@17[0] += @47) */
  for (rr=w17+0, ss=(&w47); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #307: @47 = @17[0] */
  for (rr=(&w47), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #308: @48 = @1; (@48[0] += @47) */
  casadi_copy(w1, 4, w48);
  for (rr=w48+0, ss=(&w47); rr!=w48+1; rr+=1) *rr += *ss++;
  /* #309: (@48[1] = @11) */
  for (rr=w48+1, ss=(&w11); rr!=w48+2; rr+=1) *rr = *ss++;
  /* #310: @47 = @17[1] */
  for (rr=(&w47), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #311: (@48[1] += @47) */
  for (rr=w48+1, ss=(&w47); rr!=w48+2; rr+=1) *rr += *ss++;
  /* #312: (@48[2] = @11) */
  for (rr=w48+2, ss=(&w11); rr!=w48+3; rr+=1) *rr = *ss++;
  /* #313: @47 = @17[2] */
  for (rr=(&w47), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #314: (@48[2] += @47) */
  for (rr=w48+2, ss=(&w47); rr!=w48+3; rr+=1) *rr += *ss++;
  /* #315: (@48[3] = @11) */
  for (rr=w48+3, ss=(&w11); rr!=w48+4; rr+=1) *rr = *ss++;
  /* #316: @47 = @17[3] */
  for (rr=(&w47), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #317: (@48[3] += @47) */
  for (rr=w48+3, ss=(&w47); rr!=w48+4; rr+=1) *rr += *ss++;
  /* #318: @17 = @48' */
  casadi_copy(w48, 4, w17);
  /* #319: @47 = mac(@17,@15,@11) */
  casadi_copy((&w11), 1, (&w47));
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #320: @17 = vertcat(@38, @41, @43, @47) */
  rr=w17;
  *rr++ = w38;
  *rr++ = w41;
  *rr++ = w43;
  *rr++ = w47;
  /* #321: (@19[3, 7, 11, 19] = @17) */
  for (cii=casadi_s3, rr=w19, ss=w17; cii!=casadi_s3+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #322: @49 = 00 */
  /* #323: @38 = ones(8x1,1nz) */
  w38 = 1.;
  /* #324: {NULL, @41} = vertsplit(@38) */
  w41 = w38;
  /* #325: @38 = mac(@16,@41,@11) */
  casadi_copy((&w11), 1, (&w38));
  casadi_mtimes(w16, casadi_s6, (&w41), casadi_s5, (&w38), casadi_s4, w, 0);
  /* #326: @43 = mac(@18,@41,@11) */
  casadi_copy((&w11), 1, (&w43));
  casadi_mtimes(w18, casadi_s6, (&w41), casadi_s5, (&w43), casadi_s4, w, 0);
  /* #327: @50 = vertcat(@49, @49, @38, @43) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w43;
  /* #328: @51 = @50[:2] */
  for (rr=w51, ss=w50+0; ss!=w50+2; ss+=1) *rr++ = *ss;
  /* #329: (@19[12:28:8] = @51) */
  for (rr=w19+12, ss=w51; rr!=w19+28; rr+=8) *rr = *ss++;
  /* #330: @38 = ones(8x1,1nz) */
  w38 = 1.;
  /* #331: {NULL, @43} = vertsplit(@38) */
  w43 = w38;
  /* #332: @38 = mac(@16,@43,@11) */
  casadi_copy((&w11), 1, (&w38));
  casadi_mtimes(w16, casadi_s6, (&w43), casadi_s7, (&w38), casadi_s4, w, 0);
  /* #333: @47 = mac(@18,@43,@11) */
  casadi_copy((&w11), 1, (&w47));
  casadi_mtimes(w18, casadi_s6, (&w43), casadi_s7, (&w47), casadi_s4, w, 0);
  /* #334: @51 = vertcat(@49, @49, @38, @47) */
  rr=w51;
  *rr++ = w38;
  *rr++ = w47;
  /* #335: @50 = @51[:2] */
  for (rr=w50, ss=w51+0; ss!=w51+2; ss+=1) *rr++ = *ss;
  /* #336: (@19[13:29:8] = @50) */
  for (rr=w19+13, ss=w50; rr!=w19+29; rr+=8) *rr = *ss++;
  /* #337: @38 = ones(8x1,1nz) */
  w38 = 1.;
  /* #338: {NULL, @47} = vertsplit(@38) */
  w47 = w38;
  /* #339: @38 = mac(@16,@47,@11) */
  casadi_copy((&w11), 1, (&w38));
  casadi_mtimes(w16, casadi_s6, (&w47), casadi_s8, (&w38), casadi_s4, w, 0);
  /* #340: @52 = mac(@18,@47,@11) */
  casadi_copy((&w11), 1, (&w52));
  casadi_mtimes(w18, casadi_s6, (&w47), casadi_s8, (&w52), casadi_s4, w, 0);
  /* #341: @50 = vertcat(@49, @49, @38, @52) */
  rr=w50;
  *rr++ = w38;
  *rr++ = w52;
  /* #342: @51 = @50[:2] */
  for (rr=w51, ss=w50+0; ss!=w50+2; ss+=1) *rr++ = *ss;
  /* #343: (@19[14:30:8] = @51) */
  for (rr=w19+14, ss=w51; rr!=w19+30; rr+=8) *rr = *ss++;
  /* #344: @38 = ones(8x1,1nz) */
  w38 = 1.;
  /* #345: {NULL, @52} = vertsplit(@38) */
  w52 = w38;
  /* #346: @38 = mac(@16,@52,@11) */
  casadi_copy((&w11), 1, (&w38));
  casadi_mtimes(w16, casadi_s6, (&w52), casadi_s9, (&w38), casadi_s4, w, 0);
  /* #347: @53 = mac(@18,@52,@11) */
  casadi_copy((&w11), 1, (&w53));
  casadi_mtimes(w18, casadi_s6, (&w52), casadi_s9, (&w53), casadi_s4, w, 0);
  /* #348: @51 = vertcat(@49, @49, @38, @53) */
  rr=w51;
  *rr++ = w38;
  *rr++ = w53;
  /* #349: @50 = @51[:2] */
  for (rr=w50, ss=w51+0; ss!=w51+2; ss+=1) *rr++ = *ss;
  /* #350: (@19[15:31:8] = @50) */
  for (rr=w19+15, ss=w50; rr!=w19+31; rr+=8) *rr = *ss++;
  /* #351: output[1][0] = @19 */
  casadi_copy(w19, 24, res[1]);
  /* #352: @54 = zeros(8x8,48nz) */
  casadi_clear(w54, 48);
  /* #353: @18 = input[2][0] */
  casadi_copy(arg[2], 4, w18);
  /* #354: {@38, @53, @55, @56} = vertsplit(@18) */
  w38 = w18[0];
  w53 = w18[1];
  w55 = w18[2];
  w56 = w18[3];
  /* #355: @15 = @15' */
  /* #356: @18 = (@55*@15) */
  for (i=0, rr=w18, cs=w15; i<4; ++i) (*rr++)  = (w55*(*cs++));
  /* #357: @18 = @18' */
  /* #358: @57 = @18[3] */
  for (rr=(&w57), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #359: @16 = @1; (@16[3] += @57) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w57); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #360: (@18[3] = @11) */
  for (rr=w18+3, ss=(&w11); rr!=w18+4; rr+=1) *rr = *ss++;
  /* #361: @57 = @18[2] */
  for (rr=(&w57), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #362: (@16[2] += @57) */
  for (rr=w16+2, ss=(&w57); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #363: (@18[2] = @11) */
  for (rr=w18+2, ss=(&w11); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #364: @57 = @18[1] */
  for (rr=(&w57), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #365: (@16[1] += @57) */
  for (rr=w16+1, ss=(&w57); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #366: (@18[1] = @11) */
  for (rr=w18+1, ss=(&w11); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #367: @57 = @18[0] */
  for (rr=(&w57), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #368: (@16[0] += @57) */
  for (rr=w16+0, ss=(&w57); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #369: @57 = @16[0] */
  for (rr=(&w57), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #370: @58 = @16[1] */
  for (rr=(&w58), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #371: @58 = (@57+@58) */
  w58  = (w57+w58);
  /* #372: @59 = @16[2] */
  for (rr=(&w59), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #373: @59 = (@58+@59) */
  w59  = (w58+w59);
  /* #374: @60 = @16[3] */
  for (rr=(&w60), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #375: @60 = (@59+@60) */
  w60  = (w59+w60);
  /* #376: @60 = (@0*@60) */
  w60  = (w0*w60);
  /* #377: @61 = (@60*@22) */
  w61  = (w60*w22);
  /* #378: @61 = (-@61) */
  w61 = (- w61 );
  /* #379: @15 = (@56*@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) (*rr++)  = (w56*(*cs++));
  /* #380: @15 = @15' */
  /* #381: @62 = @15[3] */
  for (rr=(&w62), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #382: @16 = @1; (@16[3] += @62) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w62); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #383: (@15[3] = @11) */
  for (rr=w15+3, ss=(&w11); rr!=w15+4; rr+=1) *rr = *ss++;
  /* #384: @62 = @15[2] */
  for (rr=(&w62), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #385: (@16[2] += @62) */
  for (rr=w16+2, ss=(&w62); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #386: (@15[2] = @11) */
  for (rr=w15+2, ss=(&w11); rr!=w15+3; rr+=1) *rr = *ss++;
  /* #387: @62 = @15[1] */
  for (rr=(&w62), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #388: (@16[1] += @62) */
  for (rr=w16+1, ss=(&w62); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #389: (@15[1] = @11) */
  for (rr=w15+1, ss=(&w11); rr!=w15+2; rr+=1) *rr = *ss++;
  /* #390: @11 = @15[0] */
  for (rr=(&w11), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #391: (@16[0] += @11) */
  for (rr=w16+0, ss=(&w11); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #392: @11 = @16[3] */
  for (rr=(&w11), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #393: @11 = (-@11) */
  w11 = (- w11 );
  /* #394: @62 = @16[0] */
  for (rr=(&w62), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #395: @63 = @16[1] */
  for (rr=(&w63), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #396: @63 = (@62+@63) */
  w63  = (w62+w63);
  /* #397: @64 = @16[2] */
  for (rr=(&w64), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #398: @64 = (@63+@64) */
  w64  = (w63+w64);
  /* #399: @11 = (@11-@64) */
  w11 -= w64;
  /* #400: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #401: @65 = (@11*@12) */
  w65  = (w11*w12);
  /* #402: @61 = (@61-@65) */
  w61 -= w65;
  /* #403: @53 = (@0*@53) */
  w53  = (w0*w53);
  /* #404: @22 = (@53*@22) */
  w22  = (w53*w22);
  /* #405: @61 = (@61+@22) */
  w61 += w22;
  /* #406: @38 = (@0*@38) */
  w38  = (w0*w38);
  /* #407: @12 = (@38*@12) */
  w12  = (w38*w12);
  /* #408: @61 = (@61-@12) */
  w61 -= w12;
  /* #409: @16 = @1; (@16[3] += @61) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w61); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #410: @64 = (@14*@64) */
  w64  = (w14*w64);
  /* #411: @12 = (@64*@28) */
  w12  = (w64*w28);
  /* #412: @59 = (@0*@59) */
  w59  = (w0*w59);
  /* #413: @22 = (@59*@21) */
  w22  = (w59*w21);
  /* #414: @12 = (@12-@22) */
  w12 -= w22;
  /* #415: @21 = (@53*@21) */
  w21  = (w53*w21);
  /* #416: @12 = (@12+@21) */
  w12 += w21;
  /* #417: @12 = (@12+@61) */
  w12 += w61;
  /* #418: @28 = (@38*@28) */
  w28  = (w38*w28);
  /* #419: @12 = (@12-@28) */
  w12 -= w28;
  /* #420: (@16[2] += @12) */
  for (rr=w16+2, ss=(&w12); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #421: @63 = (@14*@63) */
  w63  = (w14*w63);
  /* #422: @28 = (@63*@25) */
  w28  = (w63*w25);
  /* #423: @58 = (@0*@58) */
  w58  = (w0*w58);
  /* #424: @61 = (@58*@20) */
  w61  = (w58*w20);
  /* #425: @28 = (@28-@61) */
  w28 -= w61;
  /* #426: @20 = (@53*@20) */
  w20  = (w53*w20);
  /* #427: @28 = (@28+@20) */
  w28 += w20;
  /* #428: @28 = (@28+@12) */
  w28 += w12;
  /* #429: @25 = (@38*@25) */
  w25  = (w38*w25);
  /* #430: @28 = (@28-@25) */
  w28 -= w25;
  /* #431: (@16[1] += @28) */
  for (rr=w16+1, ss=(&w28); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #432: @62 = (@14*@62) */
  w62  = (w14*w62);
  /* #433: @62 = (@62*@23) */
  w62 *= w23;
  /* #434: @57 = (@0*@57) */
  w57  = (w0*w57);
  /* #435: @57 = (@57*@4) */
  w57 *= w4;
  /* #436: @62 = (@62-@57) */
  w62 -= w57;
  /* #437: @4 = (@53*@4) */
  w4  = (w53*w4);
  /* #438: @62 = (@62+@4) */
  w62 += w4;
  /* #439: @62 = (@62+@28) */
  w62 += w28;
  /* #440: @23 = (@38*@23) */
  w23  = (w38*w23);
  /* #441: @62 = (@62-@23) */
  w62 -= w23;
  /* #442: (@16[0] += @62) */
  for (rr=w16+0, ss=(&w62); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #443: @33 = (@56*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w56*(*cs++));
  /* #444: @32 = (@55*@32) */
  for (i=0, rr=w32, cs=w32; i<4; ++i) (*rr++)  = (w55*(*cs++));
  /* #445: @33 = (@33+@32) */
  for (i=0, rr=w33, cs=w32; i<4; ++i) (*rr++) += (*cs++);
  /* #446: @66 = vertcat(@16, @33) */
  rr=w66;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  /* #447: (@54[0, 8, 16, 24, 32, 36, 40, 44] = @66) */
  for (cii=casadi_s10, rr=w54, ss=w66; cii!=casadi_s10+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #448: @62 = (@60*@26) */
  w62  = (w60*w26);
  /* #449: @62 = (-@62) */
  w62 = (- w62 );
  /* #450: @23 = (@11*@13) */
  w23  = (w11*w13);
  /* #451: @62 = (@62-@23) */
  w62 -= w23;
  /* #452: @26 = (@53*@26) */
  w26  = (w53*w26);
  /* #453: @62 = (@62+@26) */
  w62 += w26;
  /* #454: @13 = (@38*@13) */
  w13  = (w38*w13);
  /* #455: @62 = (@62-@13) */
  w62 -= w13;
  /* #456: @16 = @1; (@16[3] += @62) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w62); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #457: @13 = (@64*@34) */
  w13  = (w64*w34);
  /* #458: @26 = (@59*@24) */
  w26  = (w59*w24);
  /* #459: @13 = (@13-@26) */
  w13 -= w26;
  /* #460: @24 = (@53*@24) */
  w24  = (w53*w24);
  /* #461: @13 = (@13+@24) */
  w13 += w24;
  /* #462: @13 = (@13+@62) */
  w13 += w62;
  /* #463: @34 = (@38*@34) */
  w34  = (w38*w34);
  /* #464: @13 = (@13-@34) */
  w13 -= w34;
  /* #465: (@16[2] += @13) */
  for (rr=w16+2, ss=(&w13); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #466: @63 = (@63*@30) */
  w63 *= w30;
  /* #467: @58 = (@58*@27) */
  w58 *= w27;
  /* #468: @63 = (@63-@58) */
  w63 -= w58;
  /* #469: @27 = (@53*@27) */
  w27  = (w53*w27);
  /* #470: @63 = (@63+@27) */
  w63 += w27;
  /* #471: @63 = (@63+@13) */
  w63 += w13;
  /* #472: @30 = (@38*@30) */
  w30  = (w38*w30);
  /* #473: @63 = (@63-@30) */
  w63 -= w30;
  /* #474: (@16[1] += @63) */
  for (rr=w16+1, ss=(&w63); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #475: (@16[0] += @63) */
  for (rr=w16+0, ss=(&w63); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #476: @40 = (@56*@40) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w56*(*cs++));
  /* #477: @39 = (@55*@39) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w55*(*cs++));
  /* #478: @40 = (@40+@39) */
  for (i=0, rr=w40, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #479: @66 = vertcat(@16, @40) */
  rr=w66;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  /* #480: (@54[1, 9, 17, 25, 33, 37, 41, 45] = @66) */
  for (cii=casadi_s11, rr=w54, ss=w66; cii!=casadi_s11+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #481: @63 = (@60*@31) */
  w63  = (w60*w31);
  /* #482: @63 = (-@63) */
  w63 = (- w63 );
  /* #483: @30 = (@11*@29) */
  w30  = (w11*w29);
  /* #484: @63 = (@63-@30) */
  w63 -= w30;
  /* #485: @31 = (@53*@31) */
  w31  = (w53*w31);
  /* #486: @63 = (@63+@31) */
  w63 += w31;
  /* #487: @29 = (@38*@29) */
  w29  = (w38*w29);
  /* #488: @63 = (@63-@29) */
  w63 -= w29;
  /* #489: @16 = @1; (@16[3] += @63) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w63); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #490: @64 = (@64*@37) */
  w64 *= w37;
  /* #491: @59 = (@59*@36) */
  w59 *= w36;
  /* #492: @64 = (@64-@59) */
  w64 -= w59;
  /* #493: @36 = (@53*@36) */
  w36  = (w53*w36);
  /* #494: @64 = (@64+@36) */
  w64 += w36;
  /* #495: @64 = (@64+@63) */
  w64 += w63;
  /* #496: @37 = (@38*@37) */
  w37  = (w38*w37);
  /* #497: @64 = (@64-@37) */
  w64 -= w37;
  /* #498: (@16[2] += @64) */
  for (rr=w16+2, ss=(&w64); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #499: (@16[1] += @64) */
  for (rr=w16+1, ss=(&w64); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #500: (@16[0] += @64) */
  for (rr=w16+0, ss=(&w64); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #501: @45 = (@56*@45) */
  for (i=0, rr=w45, cs=w45; i<4; ++i) (*rr++)  = (w56*(*cs++));
  /* #502: @44 = (@55*@44) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) (*rr++)  = (w55*(*cs++));
  /* #503: @45 = (@45+@44) */
  for (i=0, rr=w45, cs=w44; i<4; ++i) (*rr++) += (*cs++);
  /* #504: @66 = vertcat(@16, @45) */
  rr=w66;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<4; ++i) *rr++ = *cs++;
  /* #505: (@54[2, 10, 18, 26, 34, 38, 42, 46] = @66) */
  for (cii=casadi_s12, rr=w54, ss=w66; cii!=casadi_s12+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #506: @60 = (@60*@42) */
  w60 *= w42;
  /* #507: @60 = (-@60) */
  w60 = (- w60 );
  /* #508: @11 = (@11*@35) */
  w11 *= w35;
  /* #509: @60 = (@60-@11) */
  w60 -= w11;
  /* #510: @53 = (@53*@42) */
  w53 *= w42;
  /* #511: @60 = (@60+@53) */
  w60 += w53;
  /* #512: @38 = (@38*@35) */
  w38 *= w35;
  /* #513: @60 = (@60-@38) */
  w60 -= w38;
  /* #514: @16 = @1; (@16[3] += @60) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w60); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #515: (@16[2] += @60) */
  for (rr=w16+2, ss=(&w60); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #516: (@16[1] += @60) */
  for (rr=w16+1, ss=(&w60); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #517: (@16[0] += @60) */
  for (rr=w16+0, ss=(&w60); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #518: @48 = (@56*@48) */
  for (i=0, rr=w48, cs=w48; i<4; ++i) (*rr++)  = (w56*(*cs++));
  /* #519: @46 = (@55*@46) */
  for (i=0, rr=w46, cs=w46; i<4; ++i) (*rr++)  = (w55*(*cs++));
  /* #520: @48 = (@48+@46) */
  for (i=0, rr=w48, cs=w46; i<4; ++i) (*rr++) += (*cs++);
  /* #521: @66 = vertcat(@16, @48) */
  rr=w66;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<4; ++i) *rr++ = *cs++;
  /* #522: (@54[3, 11, 19, 27, 35, 39, 43, 47] = @66) */
  for (cii=casadi_s13, rr=w54, ss=w66; cii!=casadi_s13+8; ++cii, ++ss) rr[*cii] = *ss;
  /* #523: @41 = @41' */
  /* #524: @60 = (@56*@41) */
  w60  = (w56*w41);
  /* #525: @60 = @60' */
  /* #526: @38 = @60[0] */
  for (rr=(&w38), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #527: @16 = @1; (@16[0] += @38) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+0, ss=(&w38); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #528: @38 = @16[0] */
  for (rr=(&w38), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #529: @60 = @16[1] */
  for (rr=(&w60), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #530: @60 = (@38+@60) */
  w60  = (w38+w60);
  /* #531: @35 = @16[2] */
  for (rr=(&w35), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #532: @35 = (@60+@35) */
  w35  = (w60+w35);
  /* #533: @53 = (-@35) */
  w53 = (- w35 );
  /* #534: @42 = @16[3] */
  for (rr=(&w42), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #535: @53 = (@53-@42) */
  w53 -= w42;
  /* #536: @53 = (@14*@53) */
  w53  = (w14*w53);
  /* #537: @53 = (@9*@53) */
  w53  = (w9*w53);
  /* #538: @41 = (@55*@41) */
  w41  = (w55*w41);
  /* #539: @41 = @41' */
  /* #540: @42 = @41[0] */
  for (rr=(&w42), ss=(&w41)+0; ss!=(&w41)+1; ss+=1) *rr++ = *ss;
  /* #541: @16 = @1; (@16[0] += @42) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+0, ss=(&w42); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #542: @42 = @16[0] */
  for (rr=(&w42), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #543: @41 = @16[1] */
  for (rr=(&w41), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #544: @41 = (@42+@41) */
  w41  = (w42+w41);
  /* #545: @11 = @16[2] */
  for (rr=(&w11), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #546: @11 = (@41+@11) */
  w11  = (w41+w11);
  /* #547: @64 = @16[3] */
  for (rr=(&w64), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #548: @64 = (@11+@64) */
  w64  = (w11+w64);
  /* #549: @64 = (@0*@64) */
  w64  = (w0*w64);
  /* #550: @64 = (@10*@64) */
  w64  = (w10*w64);
  /* #551: @53 = (@53-@64) */
  w53 -= w64;
  /* #552: @16 = @1; (@16[3] += @53) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w53); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #553: @35 = (@14*@35) */
  w35  = (w14*w35);
  /* #554: @35 = (@7*@35) */
  w35  = (w7*w35);
  /* #555: @35 = (-@35) */
  w35 = (- w35 );
  /* #556: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #557: @11 = (@8*@11) */
  w11  = (w8*w11);
  /* #558: @35 = (@35-@11) */
  w35 -= w11;
  /* #559: @35 = (@35+@53) */
  w35 += w53;
  /* #560: (@16[2] += @35) */
  for (rr=w16+2, ss=(&w35); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #561: @60 = (@14*@60) */
  w60  = (w14*w60);
  /* #562: @60 = (@5*@60) */
  w60  = (w5*w60);
  /* #563: @60 = (-@60) */
  w60 = (- w60 );
  /* #564: @41 = (@0*@41) */
  w41  = (w0*w41);
  /* #565: @41 = (@6*@41) */
  w41  = (w6*w41);
  /* #566: @60 = (@60-@41) */
  w60 -= w41;
  /* #567: @60 = (@60+@35) */
  w60 += w35;
  /* #568: (@16[1] += @60) */
  for (rr=w16+1, ss=(&w60); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #569: @38 = (@14*@38) */
  w38  = (w14*w38);
  /* #570: @38 = (@2*@38) */
  w38  = (w2*w38);
  /* #571: @38 = (-@38) */
  w38 = (- w38 );
  /* #572: @42 = (@0*@42) */
  w42  = (w0*w42);
  /* #573: @42 = (@3*@42) */
  w42  = (w3*w42);
  /* #574: @38 = (@38-@42) */
  w38 -= w42;
  /* #575: @38 = (@38+@60) */
  w38 += w60;
  /* #576: (@16[0] += @38) */
  for (rr=w16+0, ss=(&w38); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #577: (@54[4:36:8] = @16) */
  for (rr=w54+4, ss=w16; rr!=w54+36; rr+=8) *rr = *ss++;
  /* #578: @43 = @43' */
  /* #579: @38 = (@56*@43) */
  w38  = (w56*w43);
  /* #580: @38 = @38' */
  /* #581: @60 = @38[0] */
  for (rr=(&w60), ss=(&w38)+0; ss!=(&w38)+1; ss+=1) *rr++ = *ss;
  /* #582: @16 = @1; (@16[1] += @60) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+1, ss=(&w60); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #583: @60 = @16[0] */
  for (rr=(&w60), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #584: @38 = @16[1] */
  for (rr=(&w38), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #585: @38 = (@60+@38) */
  w38  = (w60+w38);
  /* #586: @42 = @16[2] */
  for (rr=(&w42), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #587: @42 = (@38+@42) */
  w42  = (w38+w42);
  /* #588: @35 = (-@42) */
  w35 = (- w42 );
  /* #589: @41 = @16[3] */
  for (rr=(&w41), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #590: @35 = (@35-@41) */
  w35 -= w41;
  /* #591: @35 = (@14*@35) */
  w35  = (w14*w35);
  /* #592: @35 = (@9*@35) */
  w35  = (w9*w35);
  /* #593: @43 = (@55*@43) */
  w43  = (w55*w43);
  /* #594: @43 = @43' */
  /* #595: @41 = @43[0] */
  for (rr=(&w41), ss=(&w43)+0; ss!=(&w43)+1; ss+=1) *rr++ = *ss;
  /* #596: @16 = @1; (@16[1] += @41) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+1, ss=(&w41); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #597: @41 = @16[0] */
  for (rr=(&w41), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #598: @43 = @16[1] */
  for (rr=(&w43), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #599: @43 = (@41+@43) */
  w43  = (w41+w43);
  /* #600: @53 = @16[2] */
  for (rr=(&w53), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #601: @53 = (@43+@53) */
  w53  = (w43+w53);
  /* #602: @11 = @16[3] */
  for (rr=(&w11), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #603: @11 = (@53+@11) */
  w11  = (w53+w11);
  /* #604: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #605: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #606: @35 = (@35-@11) */
  w35 -= w11;
  /* #607: @16 = @1; (@16[3] += @35) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w35); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #608: @42 = (@14*@42) */
  w42  = (w14*w42);
  /* #609: @42 = (@7*@42) */
  w42  = (w7*w42);
  /* #610: @42 = (-@42) */
  w42 = (- w42 );
  /* #611: @53 = (@0*@53) */
  w53  = (w0*w53);
  /* #612: @53 = (@8*@53) */
  w53  = (w8*w53);
  /* #613: @42 = (@42-@53) */
  w42 -= w53;
  /* #614: @42 = (@42+@35) */
  w42 += w35;
  /* #615: (@16[2] += @42) */
  for (rr=w16+2, ss=(&w42); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #616: @38 = (@14*@38) */
  w38  = (w14*w38);
  /* #617: @38 = (@5*@38) */
  w38  = (w5*w38);
  /* #618: @38 = (-@38) */
  w38 = (- w38 );
  /* #619: @43 = (@0*@43) */
  w43  = (w0*w43);
  /* #620: @43 = (@6*@43) */
  w43  = (w6*w43);
  /* #621: @38 = (@38-@43) */
  w38 -= w43;
  /* #622: @38 = (@38+@42) */
  w38 += w42;
  /* #623: (@16[1] += @38) */
  for (rr=w16+1, ss=(&w38); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #624: @60 = (@14*@60) */
  w60  = (w14*w60);
  /* #625: @60 = (@2*@60) */
  w60  = (w2*w60);
  /* #626: @60 = (-@60) */
  w60 = (- w60 );
  /* #627: @41 = (@0*@41) */
  w41  = (w0*w41);
  /* #628: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #629: @60 = (@60-@41) */
  w60 -= w41;
  /* #630: @60 = (@60+@38) */
  w60 += w38;
  /* #631: (@16[0] += @60) */
  for (rr=w16+0, ss=(&w60); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #632: (@54[5:37:8] = @16) */
  for (rr=w54+5, ss=w16; rr!=w54+37; rr+=8) *rr = *ss++;
  /* #633: @47 = @47' */
  /* #634: @60 = (@56*@47) */
  w60  = (w56*w47);
  /* #635: @60 = @60' */
  /* #636: @38 = @60[0] */
  for (rr=(&w38), ss=(&w60)+0; ss!=(&w60)+1; ss+=1) *rr++ = *ss;
  /* #637: @16 = @1; (@16[2] += @38) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+2, ss=(&w38); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #638: @38 = @16[0] */
  for (rr=(&w38), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #639: @60 = @16[1] */
  for (rr=(&w60), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #640: @60 = (@38+@60) */
  w60  = (w38+w60);
  /* #641: @41 = @16[2] */
  for (rr=(&w41), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #642: @41 = (@60+@41) */
  w41  = (w60+w41);
  /* #643: @42 = (-@41) */
  w42 = (- w41 );
  /* #644: @43 = @16[3] */
  for (rr=(&w43), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #645: @42 = (@42-@43) */
  w42 -= w43;
  /* #646: @42 = (@14*@42) */
  w42  = (w14*w42);
  /* #647: @42 = (@9*@42) */
  w42  = (w9*w42);
  /* #648: @47 = (@55*@47) */
  w47  = (w55*w47);
  /* #649: @47 = @47' */
  /* #650: @43 = @47[0] */
  for (rr=(&w43), ss=(&w47)+0; ss!=(&w47)+1; ss+=1) *rr++ = *ss;
  /* #651: @16 = @1; (@16[2] += @43) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+2, ss=(&w43); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #652: @43 = @16[0] */
  for (rr=(&w43), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #653: @47 = @16[1] */
  for (rr=(&w47), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #654: @47 = (@43+@47) */
  w47  = (w43+w47);
  /* #655: @35 = @16[2] */
  for (rr=(&w35), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #656: @35 = (@47+@35) */
  w35  = (w47+w35);
  /* #657: @53 = @16[3] */
  for (rr=(&w53), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #658: @53 = (@35+@53) */
  w53  = (w35+w53);
  /* #659: @53 = (@0*@53) */
  w53  = (w0*w53);
  /* #660: @53 = (@10*@53) */
  w53  = (w10*w53);
  /* #661: @42 = (@42-@53) */
  w42 -= w53;
  /* #662: @16 = @1; (@16[3] += @42) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w42); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #663: @41 = (@14*@41) */
  w41  = (w14*w41);
  /* #664: @41 = (@7*@41) */
  w41  = (w7*w41);
  /* #665: @41 = (-@41) */
  w41 = (- w41 );
  /* #666: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #667: @35 = (@8*@35) */
  w35  = (w8*w35);
  /* #668: @41 = (@41-@35) */
  w41 -= w35;
  /* #669: @41 = (@41+@42) */
  w41 += w42;
  /* #670: (@16[2] += @41) */
  for (rr=w16+2, ss=(&w41); rr!=w16+3; rr+=1) *rr += *ss++;
  /* #671: @60 = (@14*@60) */
  w60  = (w14*w60);
  /* #672: @60 = (@5*@60) */
  w60  = (w5*w60);
  /* #673: @60 = (-@60) */
  w60 = (- w60 );
  /* #674: @47 = (@0*@47) */
  w47  = (w0*w47);
  /* #675: @47 = (@6*@47) */
  w47  = (w6*w47);
  /* #676: @60 = (@60-@47) */
  w60 -= w47;
  /* #677: @60 = (@60+@41) */
  w60 += w41;
  /* #678: (@16[1] += @60) */
  for (rr=w16+1, ss=(&w60); rr!=w16+2; rr+=1) *rr += *ss++;
  /* #679: @38 = (@14*@38) */
  w38  = (w14*w38);
  /* #680: @38 = (@2*@38) */
  w38  = (w2*w38);
  /* #681: @38 = (-@38) */
  w38 = (- w38 );
  /* #682: @43 = (@0*@43) */
  w43  = (w0*w43);
  /* #683: @43 = (@3*@43) */
  w43  = (w3*w43);
  /* #684: @38 = (@38-@43) */
  w38 -= w43;
  /* #685: @38 = (@38+@60) */
  w38 += w60;
  /* #686: (@16[0] += @38) */
  for (rr=w16+0, ss=(&w38); rr!=w16+1; rr+=1) *rr += *ss++;
  /* #687: (@54[6:38:8] = @16) */
  for (rr=w54+6, ss=w16; rr!=w54+38; rr+=8) *rr = *ss++;
  /* #688: @52 = @52' */
  /* #689: @56 = (@56*@52) */
  w56 *= w52;
  /* #690: @56 = @56' */
  /* #691: @38 = @56[0] */
  for (rr=(&w38), ss=(&w56)+0; ss!=(&w56)+1; ss+=1) *rr++ = *ss;
  /* #692: @16 = @1; (@16[3] += @38) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w38); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #693: @38 = @16[0] */
  for (rr=(&w38), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #694: @56 = @16[1] */
  for (rr=(&w56), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #695: @56 = (@38+@56) */
  w56  = (w38+w56);
  /* #696: @60 = @16[2] */
  for (rr=(&w60), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #697: @60 = (@56+@60) */
  w60  = (w56+w60);
  /* #698: @43 = (-@60) */
  w43 = (- w60 );
  /* #699: @41 = @16[3] */
  for (rr=(&w41), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #700: @43 = (@43-@41) */
  w43 -= w41;
  /* #701: @43 = (@14*@43) */
  w43  = (w14*w43);
  /* #702: @9 = (@9*@43) */
  w9 *= w43;
  /* #703: @55 = (@55*@52) */
  w55 *= w52;
  /* #704: @55 = @55' */
  /* #705: @52 = @55[0] */
  for (rr=(&w52), ss=(&w55)+0; ss!=(&w55)+1; ss+=1) *rr++ = *ss;
  /* #706: @16 = @1; (@16[3] += @52) */
  casadi_copy(w1, 4, w16);
  for (rr=w16+3, ss=(&w52); rr!=w16+4; rr+=1) *rr += *ss++;
  /* #707: @52 = @16[0] */
  for (rr=(&w52), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #708: @55 = @16[1] */
  for (rr=(&w55), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #709: @55 = (@52+@55) */
  w55  = (w52+w55);
  /* #710: @43 = @16[2] */
  for (rr=(&w43), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #711: @43 = (@55+@43) */
  w43  = (w55+w43);
  /* #712: @41 = @16[3] */
  for (rr=(&w41), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #713: @41 = (@43+@41) */
  w41  = (w43+w41);
  /* #714: @41 = (@0*@41) */
  w41  = (w0*w41);
  /* #715: @10 = (@10*@41) */
  w10 *= w41;
  /* #716: @9 = (@9-@10) */
  w9 -= w10;
  /* #717: (@1[3] += @9) */
  for (rr=w1+3, ss=(&w9); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #718: @60 = (@14*@60) */
  w60  = (w14*w60);
  /* #719: @7 = (@7*@60) */
  w7 *= w60;
  /* #720: @7 = (-@7) */
  w7 = (- w7 );
  /* #721: @43 = (@0*@43) */
  w43  = (w0*w43);
  /* #722: @8 = (@8*@43) */
  w8 *= w43;
  /* #723: @7 = (@7-@8) */
  w7 -= w8;
  /* #724: @7 = (@7+@9) */
  w7 += w9;
  /* #725: (@1[2] += @7) */
  for (rr=w1+2, ss=(&w7); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #726: @56 = (@14*@56) */
  w56  = (w14*w56);
  /* #727: @5 = (@5*@56) */
  w5 *= w56;
  /* #728: @5 = (-@5) */
  w5 = (- w5 );
  /* #729: @55 = (@0*@55) */
  w55  = (w0*w55);
  /* #730: @6 = (@6*@55) */
  w6 *= w55;
  /* #731: @5 = (@5-@6) */
  w5 -= w6;
  /* #732: @5 = (@5+@7) */
  w5 += w7;
  /* #733: (@1[1] += @5) */
  for (rr=w1+1, ss=(&w5); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #734: @14 = (@14*@38) */
  w14 *= w38;
  /* #735: @2 = (@2*@14) */
  w2 *= w14;
  /* #736: @2 = (-@2) */
  w2 = (- w2 );
  /* #737: @0 = (@0*@52) */
  w0 *= w52;
  /* #738: @3 = (@3*@0) */
  w3 *= w0;
  /* #739: @2 = (@2-@3) */
  w2 -= w3;
  /* #740: @2 = (@2+@5) */
  w2 += w5;
  /* #741: (@1[0] += @2) */
  for (rr=w1+0, ss=(&w2); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #742: (@54[7:39:8] = @1) */
  for (rr=w54+7, ss=w1; rr!=w54+39; rr+=8) *rr = *ss++;
  /* #743: @67 = @54' */
  casadi_trans(w54,casadi_s14, w67, casadi_s14, iw);
  /* #744: output[2][0] = @67 */
  casadi_copy(w67, 48, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s16;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s19;
    case 2: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 233;
  return 0;
}

CASADI_SYMBOL_EXPORT int transition_model_point_mass_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 9*sizeof(casadi_int);
  if (sz_w) *sz_w = 233*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
