/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[8] = {10, 1, 0, 4, 2, 3, 4, 5};
static const casadi_int casadi_s5[3] = {1, 0, 0};

/* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt:(i0[8],i1[2],i2[],i3[])->(o0,o1[10x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5, w6, w7, *w8=w+11;
  /* #0: @0 = 0.125 */
  w0 = 1.2500000000000000e-01;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 4, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #5: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @4 = (@2+@4) */
  w4  = (w2+w4);
  /* #7: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #8: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #9: @3 = (@3+@5) */
  w3 += w5;
  /* #10: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @5 = (@4+@5) */
  w5  = (w4+w5);
  /* #12: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #13: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #14: @3 = (@3+@6) */
  w3 += w6;
  /* #15: @6 = @1[3] */
  for (rr=(&w6), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @6 = (@5+@6) */
  w6  = (w5+w6);
  /* #17: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #18: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #19: @3 = (@3+@7) */
  w3 += w7;
  /* #20: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #21: @1 = zeros(10x1,4nz) */
  casadi_clear(w1, 4);
  /* #22: @8 = zeros(4x1) */
  casadi_clear(w8, 4);
  /* #23: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #24: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #25: (@8[3] += @6) */
  for (rr=w8+3, ss=(&w6); rr!=w8+4; rr+=1) *rr += *ss++;
  /* #26: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #27: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #28: @6 = (@6+@5) */
  w6 += w5;
  /* #29: (@8[2] += @6) */
  for (rr=w8+2, ss=(&w6); rr!=w8+3; rr+=1) *rr += *ss++;
  /* #30: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #31: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #32: @6 = (@6+@4) */
  w6 += w4;
  /* #33: (@8[1] += @6) */
  for (rr=w8+1, ss=(&w6); rr!=w8+2; rr+=1) *rr += *ss++;
  /* #34: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #35: @0 = (@0*@2) */
  w0 *= w2;
  /* #36: @6 = (@6+@0) */
  w6 += w0;
  /* #37: (@8[0] += @6) */
  for (rr=w8+0, ss=(&w6); rr!=w8+1; rr+=1) *rr += *ss++;
  /* #38: @6 = @8[0] */
  for (rr=(&w6), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #39: (@1[0] = @6) */
  for (rr=w1+0, ss=(&w6); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #40: @6 = @8[1] */
  for (rr=(&w6), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #41: (@1[1] = @6) */
  for (rr=w1+1, ss=(&w6); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #42: @6 = @8[2] */
  for (rr=(&w6), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #43: (@1[2] = @6) */
  for (rr=w1+2, ss=(&w6); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #44: @6 = @8[3] */
  for (rr=(&w6), ss=w8+3; ss!=w8+4; ss+=1) *rr++ = *ss;
  /* #45: (@1[3] = @6) */
  for (rr=w1+3, ss=(&w6); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #46: output[1][0] = @1 */
  casadi_copy(w1, 4, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_4_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 15*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
