/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[59] = {18, 6, 0, 8, 16, 32, 48, 49, 50, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 0, 1};
static const casadi_int casadi_s5[3] = {6, 0, 0};

/* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt:(i0[16],i1[2],i2[],i3[],i4[])->(o0[6],o1[18x6,50nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, *w27=w+35, *w28=w+43, *w29=w+51, *w30=w+59, *w31=w+67, *w32=w+69, *w33=w+119, *w34=w+122, w35, w36;
  /* #0: @0 = 0.0625 */
  w0 = 6.2500000000000000e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 8, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: @11 = @1[4] */
  for (rr=(&w11), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@9+@11) */
  w11  = (w9+w11);
  /* #22: @12 = sin(@11) */
  w12 = sin( w11 );
  /* #23: @13 = (@0*@12) */
  w13  = (w0*w12);
  /* #24: @4 = (@4+@13) */
  w4 += w13;
  /* #25: @13 = @1[5] */
  for (rr=(&w13), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #26: @13 = (@11+@13) */
  w13  = (w11+w13);
  /* #27: @14 = sin(@13) */
  w14 = sin( w13 );
  /* #28: @15 = (@0*@14) */
  w15  = (w0*w14);
  /* #29: @4 = (@4+@15) */
  w4 += w15;
  /* #30: @15 = @1[6] */
  for (rr=(&w15), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #31: @15 = (@13+@15) */
  w15  = (w13+w15);
  /* #32: @16 = sin(@15) */
  w16 = sin( w15 );
  /* #33: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #34: @4 = (@4+@17) */
  w4 += w17;
  /* #35: @17 = @1[7] */
  for (rr=(&w17), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #36: @17 = (@15+@17) */
  w17  = (w15+w17);
  /* #37: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #38: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #39: @4 = (@4+@19) */
  w4 += w19;
  /* #40: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #41: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #42: @4 = (@0*@2) */
  w4  = (w0*w2);
  /* #43: @19 = (-@4) */
  w19 = (- w4 );
  /* #44: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #45: @20 = (@0*@5) */
  w20  = (w0*w5);
  /* #46: @19 = (@19-@20) */
  w19 -= w20;
  /* #47: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #48: @21 = (@0*@7) */
  w21  = (w0*w7);
  /* #49: @19 = (@19-@21) */
  w19 -= w21;
  /* #50: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #51: @22 = (@0*@9) */
  w22  = (w0*w9);
  /* #52: @19 = (@19-@22) */
  w19 -= w22;
  /* #53: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #54: @23 = (@0*@11) */
  w23  = (w0*w11);
  /* #55: @19 = (@19-@23) */
  w19 -= w23;
  /* #56: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #57: @24 = (@0*@13) */
  w24  = (w0*w13);
  /* #58: @19 = (@19-@24) */
  w19 -= w24;
  /* #59: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #60: @25 = (@0*@15) */
  w25  = (w0*w15);
  /* #61: @19 = (@19-@25) */
  w19 -= w25;
  /* #62: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #63: @26 = (@0*@17) */
  w26  = (w0*w17);
  /* #64: @19 = (@19-@26) */
  w19 -= w26;
  /* #65: output[0][1] = @19 */
  if (res[0]) res[0][1] = w19;
  /* #66: @19 = 0 */
  w19 = 0.;
  /* #67: @1 = zeros(8x1) */
  casadi_clear(w1, 8);
  /* #68: @27 = @1; (@27[7] += @26) */
  casadi_copy(w1, 8, w27);
  for (rr=w27+7, ss=(&w26); rr!=w27+8; rr+=1) *rr += *ss++;
  /* #69: @26 = (@26+@25) */
  w26 += w25;
  /* #70: (@27[6] += @26) */
  for (rr=w27+6, ss=(&w26); rr!=w27+7; rr+=1) *rr += *ss++;
  /* #71: @26 = (@26+@24) */
  w26 += w24;
  /* #72: (@27[5] += @26) */
  for (rr=w27+5, ss=(&w26); rr!=w27+6; rr+=1) *rr += *ss++;
  /* #73: @26 = (@26+@23) */
  w26 += w23;
  /* #74: (@27[4] += @26) */
  for (rr=w27+4, ss=(&w26); rr!=w27+5; rr+=1) *rr += *ss++;
  /* #75: @26 = (@26+@22) */
  w26 += w22;
  /* #76: (@27[3] += @26) */
  for (rr=w27+3, ss=(&w26); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #77: @26 = (@26+@21) */
  w26 += w21;
  /* #78: (@27[2] += @26) */
  for (rr=w27+2, ss=(&w26); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #79: @26 = (@26+@20) */
  w26 += w20;
  /* #80: (@27[1] += @26) */
  for (rr=w27+1, ss=(&w26); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #81: @26 = (@26+@4) */
  w26 += w4;
  /* #82: (@27[0] += @26) */
  for (rr=w27+0, ss=(&w26); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #83: @26 = @27[0] */
  for (rr=(&w26), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #84: @28 = @1; (@28[0] = @26) */
  casadi_copy(w1, 8, w28);
  for (rr=w28+0, ss=(&w26); rr!=w28+1; rr+=1) *rr = *ss++;
  /* #85: @26 = @27[1] */
  for (rr=(&w26), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #86: (@28[1] = @26) */
  for (rr=w28+1, ss=(&w26); rr!=w28+2; rr+=1) *rr = *ss++;
  /* #87: @26 = @27[2] */
  for (rr=(&w26), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #88: (@28[2] = @26) */
  for (rr=w28+2, ss=(&w26); rr!=w28+3; rr+=1) *rr = *ss++;
  /* #89: @26 = @27[3] */
  for (rr=(&w26), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #90: (@28[3] = @26) */
  for (rr=w28+3, ss=(&w26); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #91: @26 = @27[4] */
  for (rr=(&w26), ss=w27+4; ss!=w27+5; ss+=1) *rr++ = *ss;
  /* #92: (@28[4] = @26) */
  for (rr=w28+4, ss=(&w26); rr!=w28+5; rr+=1) *rr = *ss++;
  /* #93: @26 = @27[5] */
  for (rr=(&w26), ss=w27+5; ss!=w27+6; ss+=1) *rr++ = *ss;
  /* #94: (@28[5] = @26) */
  for (rr=w28+5, ss=(&w26); rr!=w28+6; rr+=1) *rr = *ss++;
  /* #95: @26 = @27[6] */
  for (rr=(&w26), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #96: (@28[6] = @26) */
  for (rr=w28+6, ss=(&w26); rr!=w28+7; rr+=1) *rr = *ss++;
  /* #97: @26 = @27[7] */
  for (rr=(&w26), ss=w27+7; ss!=w27+8; ss+=1) *rr++ = *ss;
  /* #98: (@28[7] = @26) */
  for (rr=w28+7, ss=(&w26); rr!=w28+8; rr+=1) *rr = *ss++;
  /* #99: @27 = @28' */
  casadi_copy(w28, 8, w27);
  /* #100: @29 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+8 : 0, 8, w29);
  /* #101: @26 = mac(@27,@29,@19) */
  casadi_copy((&w19), 1, (&w26));
  for (i=0, rr=(&w26); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w29+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #102: output[0][2] = @26 */
  if (res[0]) res[0][2] = w26;
  /* #103: @26 = -0.0625 */
  w26 = -6.2500000000000000e-02;
  /* #104: @4 = (@26*@18) */
  w4  = (w26*w18);
  /* #105: @20 = (-@4) */
  w20 = (- w4 );
  /* #106: @27 = @1; (@27[7] += @20) */
  casadi_copy(w1, 8, w27);
  for (rr=w27+7, ss=(&w20); rr!=w27+8; rr+=1) *rr += *ss++;
  /* #107: @20 = (@26*@16) */
  w20  = (w26*w16);
  /* #108: @20 = (-@20) */
  w20 = (- w20 );
  /* #109: @20 = (@20-@4) */
  w20 -= w4;
  /* #110: (@27[6] += @20) */
  for (rr=w27+6, ss=(&w20); rr!=w27+7; rr+=1) *rr += *ss++;
  /* #111: @4 = (@26*@14) */
  w4  = (w26*w14);
  /* #112: @20 = (@20-@4) */
  w20 -= w4;
  /* #113: (@27[5] += @20) */
  for (rr=w27+5, ss=(&w20); rr!=w27+6; rr+=1) *rr += *ss++;
  /* #114: @4 = (@26*@12) */
  w4  = (w26*w12);
  /* #115: @20 = (@20-@4) */
  w20 -= w4;
  /* #116: (@27[4] += @20) */
  for (rr=w27+4, ss=(&w20); rr!=w27+5; rr+=1) *rr += *ss++;
  /* #117: @4 = (@26*@10) */
  w4  = (w26*w10);
  /* #118: @20 = (@20-@4) */
  w20 -= w4;
  /* #119: (@27[3] += @20) */
  for (rr=w27+3, ss=(&w20); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #120: @4 = (@26*@8) */
  w4  = (w26*w8);
  /* #121: @20 = (@20-@4) */
  w20 -= w4;
  /* #122: (@27[2] += @20) */
  for (rr=w27+2, ss=(&w20); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #123: @4 = (@26*@6) */
  w4  = (w26*w6);
  /* #124: @20 = (@20-@4) */
  w20 -= w4;
  /* #125: (@27[1] += @20) */
  for (rr=w27+1, ss=(&w20); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #126: @4 = (@26*@3) */
  w4  = (w26*w3);
  /* #127: @20 = (@20-@4) */
  w20 -= w4;
  /* #128: (@27[0] += @20) */
  for (rr=w27+0, ss=(&w20); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #129: @20 = @27[0] */
  for (rr=(&w20), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #130: @30 = @1; (@30[0] = @20) */
  casadi_copy(w1, 8, w30);
  for (rr=w30+0, ss=(&w20); rr!=w30+1; rr+=1) *rr = *ss++;
  /* #131: @20 = @27[1] */
  for (rr=(&w20), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #132: (@30[1] = @20) */
  for (rr=w30+1, ss=(&w20); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #133: @20 = @27[2] */
  for (rr=(&w20), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #134: (@30[2] = @20) */
  for (rr=w30+2, ss=(&w20); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #135: @20 = @27[3] */
  for (rr=(&w20), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #136: (@30[3] = @20) */
  for (rr=w30+3, ss=(&w20); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #137: @20 = @27[4] */
  for (rr=(&w20), ss=w27+4; ss!=w27+5; ss+=1) *rr++ = *ss;
  /* #138: (@30[4] = @20) */
  for (rr=w30+4, ss=(&w20); rr!=w30+5; rr+=1) *rr = *ss++;
  /* #139: @20 = @27[5] */
  for (rr=(&w20), ss=w27+5; ss!=w27+6; ss+=1) *rr++ = *ss;
  /* #140: (@30[5] = @20) */
  for (rr=w30+5, ss=(&w20); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #141: @20 = @27[6] */
  for (rr=(&w20), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #142: (@30[6] = @20) */
  for (rr=w30+6, ss=(&w20); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #143: @20 = @27[7] */
  for (rr=(&w20), ss=w27+7; ss!=w27+8; ss+=1) *rr++ = *ss;
  /* #144: (@30[7] = @20) */
  for (rr=w30+7, ss=(&w20); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #145: @27 = @30' */
  casadi_copy(w30, 8, w27);
  /* #146: @20 = mac(@27,@29,@19) */
  casadi_copy((&w19), 1, (&w20));
  for (i=0, rr=(&w20); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w29+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #147: output[0][3] = @20 */
  if (res[0]) res[0][3] = w20;
  /* #148: @31 = input[1][0] */
  casadi_copy(arg[1], 2, w31);
  /* #149: output[0][4] = @31 */
  if (res[0]) casadi_copy(w31, 2, res[0]+4);
  /* #150: @32 = zeros(18x6,50nz) */
  casadi_clear(w32, 50);
  /* #151: @33 = ones(6x1,3nz) */
  casadi_fill(w33, 3, 1.);
  /* #152: {@20, NULL, NULL, NULL, @31} = vertsplit(@33) */
  w20 = w33[0];
  casadi_copy(w33+1, 2, w31);
  /* #153: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #154: @4 = (@17*@20) */
  w4  = (w17*w20);
  /* #155: @27 = @1; (@27[7] += @4) */
  casadi_copy(w1, 8, w27);
  for (rr=w27+7, ss=(&w4); rr!=w27+8; rr+=1) *rr += *ss++;
  /* #156: @21 = (@15*@20) */
  w21  = (w15*w20);
  /* #157: @4 = (@4+@21) */
  w4 += w21;
  /* #158: (@27[6] += @4) */
  for (rr=w27+6, ss=(&w4); rr!=w27+7; rr+=1) *rr += *ss++;
  /* #159: @21 = (@13*@20) */
  w21  = (w13*w20);
  /* #160: @4 = (@4+@21) */
  w4 += w21;
  /* #161: (@27[5] += @4) */
  for (rr=w27+5, ss=(&w4); rr!=w27+6; rr+=1) *rr += *ss++;
  /* #162: @21 = (@11*@20) */
  w21  = (w11*w20);
  /* #163: @4 = (@4+@21) */
  w4 += w21;
  /* #164: (@27[4] += @4) */
  for (rr=w27+4, ss=(&w4); rr!=w27+5; rr+=1) *rr += *ss++;
  /* #165: @21 = (@9*@20) */
  w21  = (w9*w20);
  /* #166: @4 = (@4+@21) */
  w4 += w21;
  /* #167: (@27[3] += @4) */
  for (rr=w27+3, ss=(&w4); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #168: @21 = (@7*@20) */
  w21  = (w7*w20);
  /* #169: @4 = (@4+@21) */
  w4 += w21;
  /* #170: (@27[2] += @4) */
  for (rr=w27+2, ss=(&w4); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #171: @21 = (@5*@20) */
  w21  = (w5*w20);
  /* #172: @4 = (@4+@21) */
  w4 += w21;
  /* #173: (@27[1] += @4) */
  for (rr=w27+1, ss=(&w4); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #174: @20 = (@2*@20) */
  w20  = (w2*w20);
  /* #175: @4 = (@4+@20) */
  w4 += w20;
  /* #176: (@27[0] += @4) */
  for (rr=w27+0, ss=(&w4); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #177: @4 = @27[0] */
  for (rr=(&w4), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #178: (@32[0] = @4) */
  for (rr=w32+0, ss=(&w4); rr!=w32+1; rr+=1) *rr = *ss++;
  /* #179: @4 = @27[1] */
  for (rr=(&w4), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #180: (@32[1] = @4) */
  for (rr=w32+1, ss=(&w4); rr!=w32+2; rr+=1) *rr = *ss++;
  /* #181: @4 = @27[2] */
  for (rr=(&w4), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #182: (@32[2] = @4) */
  for (rr=w32+2, ss=(&w4); rr!=w32+3; rr+=1) *rr = *ss++;
  /* #183: @4 = @27[3] */
  for (rr=(&w4), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #184: (@32[3] = @4) */
  for (rr=w32+3, ss=(&w4); rr!=w32+4; rr+=1) *rr = *ss++;
  /* #185: @4 = @27[4] */
  for (rr=(&w4), ss=w27+4; ss!=w27+5; ss+=1) *rr++ = *ss;
  /* #186: (@32[4] = @4) */
  for (rr=w32+4, ss=(&w4); rr!=w32+5; rr+=1) *rr = *ss++;
  /* #187: @4 = @27[5] */
  for (rr=(&w4), ss=w27+5; ss!=w27+6; ss+=1) *rr++ = *ss;
  /* #188: (@32[5] = @4) */
  for (rr=w32+5, ss=(&w4); rr!=w32+6; rr+=1) *rr = *ss++;
  /* #189: @4 = @27[6] */
  for (rr=(&w4), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #190: (@32[6] = @4) */
  for (rr=w32+6, ss=(&w4); rr!=w32+7; rr+=1) *rr = *ss++;
  /* #191: @4 = @27[7] */
  for (rr=(&w4), ss=w27+7; ss!=w27+8; ss+=1) *rr++ = *ss;
  /* #192: (@32[7] = @4) */
  for (rr=w32+7, ss=(&w4); rr!=w32+8; rr+=1) *rr = *ss++;
  /* #193: @4 = @31[0] */
  for (rr=(&w4), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  /* #194: (@32[48] = @4) */
  for (rr=w32+48, ss=(&w4); rr!=w32+49; rr+=1) *rr = *ss++;
  /* #195: @4 = @31[1] */
  for (rr=(&w4), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #196: (@32[49] = @4) */
  for (rr=w32+49, ss=(&w4); rr!=w32+50; rr+=1) *rr = *ss++;
  /* #197: @4 = ones(6x1,1nz) */
  w4 = 1.;
  /* #198: {NULL, @20, NULL, NULL, NULL} = vertsplit(@4) */
  w20 = w4;
  /* #199: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #200: @4 = (@18*@20) */
  w4  = (w18*w20);
  /* #201: @27 = @1; (@27[7] += @4) */
  casadi_copy(w1, 8, w27);
  for (rr=w27+7, ss=(&w4); rr!=w27+8; rr+=1) *rr += *ss++;
  /* #202: @21 = (@16*@20) */
  w21  = (w16*w20);
  /* #203: @21 = (@21+@4) */
  w21 += w4;
  /* #204: (@27[6] += @21) */
  for (rr=w27+6, ss=(&w21); rr!=w27+7; rr+=1) *rr += *ss++;
  /* #205: @4 = (@14*@20) */
  w4  = (w14*w20);
  /* #206: @4 = (@4+@21) */
  w4 += w21;
  /* #207: (@27[5] += @4) */
  for (rr=w27+5, ss=(&w4); rr!=w27+6; rr+=1) *rr += *ss++;
  /* #208: @21 = (@12*@20) */
  w21  = (w12*w20);
  /* #209: @21 = (@21+@4) */
  w21 += w4;
  /* #210: (@27[4] += @21) */
  for (rr=w27+4, ss=(&w21); rr!=w27+5; rr+=1) *rr += *ss++;
  /* #211: @4 = (@10*@20) */
  w4  = (w10*w20);
  /* #212: @4 = (@4+@21) */
  w4 += w21;
  /* #213: (@27[3] += @4) */
  for (rr=w27+3, ss=(&w4); rr!=w27+4; rr+=1) *rr += *ss++;
  /* #214: @21 = (@8*@20) */
  w21  = (w8*w20);
  /* #215: @21 = (@21+@4) */
  w21 += w4;
  /* #216: (@27[2] += @21) */
  for (rr=w27+2, ss=(&w21); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #217: @4 = (@6*@20) */
  w4  = (w6*w20);
  /* #218: @4 = (@4+@21) */
  w4 += w21;
  /* #219: (@27[1] += @4) */
  for (rr=w27+1, ss=(&w4); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #220: @20 = (@3*@20) */
  w20  = (w3*w20);
  /* #221: @20 = (@20+@4) */
  w20 += w4;
  /* #222: (@27[0] += @20) */
  for (rr=w27+0, ss=(&w20); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #223: @20 = @27[0] */
  for (rr=(&w20), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #224: (@32[8] = @20) */
  for (rr=w32+8, ss=(&w20); rr!=w32+9; rr+=1) *rr = *ss++;
  /* #225: @20 = @27[1] */
  for (rr=(&w20), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #226: (@32[9] = @20) */
  for (rr=w32+9, ss=(&w20); rr!=w32+10; rr+=1) *rr = *ss++;
  /* #227: @20 = @27[2] */
  for (rr=(&w20), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #228: (@32[10] = @20) */
  for (rr=w32+10, ss=(&w20); rr!=w32+11; rr+=1) *rr = *ss++;
  /* #229: @20 = @27[3] */
  for (rr=(&w20), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #230: (@32[11] = @20) */
  for (rr=w32+11, ss=(&w20); rr!=w32+12; rr+=1) *rr = *ss++;
  /* #231: @20 = @27[4] */
  for (rr=(&w20), ss=w27+4; ss!=w27+5; ss+=1) *rr++ = *ss;
  /* #232: (@32[12] = @20) */
  for (rr=w32+12, ss=(&w20); rr!=w32+13; rr+=1) *rr = *ss++;
  /* #233: @20 = @27[5] */
  for (rr=(&w20), ss=w27+5; ss!=w27+6; ss+=1) *rr++ = *ss;
  /* #234: (@32[13] = @20) */
  for (rr=w32+13, ss=(&w20); rr!=w32+14; rr+=1) *rr = *ss++;
  /* #235: @20 = @27[6] */
  for (rr=(&w20), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #236: (@32[14] = @20) */
  for (rr=w32+14, ss=(&w20); rr!=w32+15; rr+=1) *rr = *ss++;
  /* #237: @20 = @27[7] */
  for (rr=(&w20), ss=w27+7; ss!=w27+8; ss+=1) *rr++ = *ss;
  /* #238: (@32[15] = @20) */
  for (rr=w32+15, ss=(&w20); rr!=w32+16; rr+=1) *rr = *ss++;
  /* #239: @20 = ones(6x1,1nz) */
  w20 = 1.;
  /* #240: {NULL, NULL, @4, NULL, NULL} = vertsplit(@20) */
  w4 = w20;
  /* #241: @29 = @29' */
  /* #242: @27 = (@4*@29) */
  for (i=0, rr=w27, cs=w29; i<8; ++i) (*rr++)  = (w4*(*cs++));
  /* #243: @27 = @27' */
  /* #244: @20 = @27[7] */
  for (rr=(&w20), ss=w27+7; ss!=w27+8; ss+=1) *rr++ = *ss;
  /* #245: @34 = @1; (@34[7] += @20) */
  casadi_copy(w1, 8, w34);
  for (rr=w34+7, ss=(&w20); rr!=w34+8; rr+=1) *rr += *ss++;
  /* #246: (@27[7] = @19) */
  for (rr=w27+7, ss=(&w19); rr!=w27+8; rr+=1) *rr = *ss++;
  /* #247: @20 = @27[6] */
  for (rr=(&w20), ss=w27+6; ss!=w27+7; ss+=1) *rr++ = *ss;
  /* #248: (@34[6] += @20) */
  for (rr=w34+6, ss=(&w20); rr!=w34+7; rr+=1) *rr += *ss++;
  /* #249: (@27[6] = @19) */
  for (rr=w27+6, ss=(&w19); rr!=w27+7; rr+=1) *rr = *ss++;
  /* #250: @20 = @27[5] */
  for (rr=(&w20), ss=w27+5; ss!=w27+6; ss+=1) *rr++ = *ss;
  /* #251: (@34[5] += @20) */
  for (rr=w34+5, ss=(&w20); rr!=w34+6; rr+=1) *rr += *ss++;
  /* #252: (@27[5] = @19) */
  for (rr=w27+5, ss=(&w19); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #253: @20 = @27[4] */
  for (rr=(&w20), ss=w27+4; ss!=w27+5; ss+=1) *rr++ = *ss;
  /* #254: (@34[4] += @20) */
  for (rr=w34+4, ss=(&w20); rr!=w34+5; rr+=1) *rr += *ss++;
  /* #255: (@27[4] = @19) */
  for (rr=w27+4, ss=(&w19); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #256: @20 = @27[3] */
  for (rr=(&w20), ss=w27+3; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #257: (@34[3] += @20) */
  for (rr=w34+3, ss=(&w20); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #258: (@27[3] = @19) */
  for (rr=w27+3, ss=(&w19); rr!=w27+4; rr+=1) *rr = *ss++;
  /* #259: @20 = @27[2] */
  for (rr=(&w20), ss=w27+2; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #260: (@34[2] += @20) */
  for (rr=w34+2, ss=(&w20); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #261: (@27[2] = @19) */
  for (rr=w27+2, ss=(&w19); rr!=w27+3; rr+=1) *rr = *ss++;
  /* #262: @20 = @27[1] */
  for (rr=(&w20), ss=w27+1; ss!=w27+2; ss+=1) *rr++ = *ss;
  /* #263: (@34[1] += @20) */
  for (rr=w34+1, ss=(&w20); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #264: (@27[1] = @19) */
  for (rr=w27+1, ss=(&w19); rr!=w27+2; rr+=1) *rr = *ss++;
  /* #265: @20 = @27[0] */
  for (rr=(&w20), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #266: (@34[0] += @20) */
  for (rr=w34+0, ss=(&w20); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #267: @20 = @34[0] */
  for (rr=(&w20), ss=w34+0; ss!=w34+1; ss+=1) *rr++ = *ss;
  /* #268: @21 = @34[1] */
  for (rr=(&w21), ss=w34+1; ss!=w34+2; ss+=1) *rr++ = *ss;
  /* #269: @21 = (@20+@21) */
  w21  = (w20+w21);
  /* #270: @22 = @34[2] */
  for (rr=(&w22), ss=w34+2; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #271: @22 = (@21+@22) */
  w22  = (w21+w22);
  /* #272: @23 = @34[3] */
  for (rr=(&w23), ss=w34+3; ss!=w34+4; ss+=1) *rr++ = *ss;
  /* #273: @23 = (@22+@23) */
  w23  = (w22+w23);
  /* #274: @24 = @34[4] */
  for (rr=(&w24), ss=w34+4; ss!=w34+5; ss+=1) *rr++ = *ss;
  /* #275: @24 = (@23+@24) */
  w24  = (w23+w24);
  /* #276: @25 = @34[5] */
  for (rr=(&w25), ss=w34+5; ss!=w34+6; ss+=1) *rr++ = *ss;
  /* #277: @25 = (@24+@25) */
  w25  = (w24+w25);
  /* #278: @35 = @34[6] */
  for (rr=(&w35), ss=w34+6; ss!=w34+7; ss+=1) *rr++ = *ss;
  /* #279: @35 = (@25+@35) */
  w35  = (w25+w35);
  /* #280: @36 = @34[7] */
  for (rr=(&w36), ss=w34+7; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #281: @36 = (@35+@36) */
  w36  = (w35+w36);
  /* #282: @36 = (@0*@36) */
  w36  = (w0*w36);
  /* #283: @18 = (@18*@36) */
  w18 *= w36;
  /* #284: @18 = (-@18) */
  w18 = (- w18 );
  /* #285: @34 = @1; (@34[7] += @18) */
  casadi_copy(w1, 8, w34);
  for (rr=w34+7, ss=(&w18); rr!=w34+8; rr+=1) *rr += *ss++;
  /* #286: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #287: @16 = (@16*@35) */
  w16 *= w35;
  /* #288: @18 = (@18-@16) */
  w18 -= w16;
  /* #289: (@34[6] += @18) */
  for (rr=w34+6, ss=(&w18); rr!=w34+7; rr+=1) *rr += *ss++;
  /* #290: @25 = (@0*@25) */
  w25  = (w0*w25);
  /* #291: @14 = (@14*@25) */
  w14 *= w25;
  /* #292: @18 = (@18-@14) */
  w18 -= w14;
  /* #293: (@34[5] += @18) */
  for (rr=w34+5, ss=(&w18); rr!=w34+6; rr+=1) *rr += *ss++;
  /* #294: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #295: @12 = (@12*@24) */
  w12 *= w24;
  /* #296: @18 = (@18-@12) */
  w18 -= w12;
  /* #297: (@34[4] += @18) */
  for (rr=w34+4, ss=(&w18); rr!=w34+5; rr+=1) *rr += *ss++;
  /* #298: @23 = (@0*@23) */
  w23  = (w0*w23);
  /* #299: @10 = (@10*@23) */
  w10 *= w23;
  /* #300: @18 = (@18-@10) */
  w18 -= w10;
  /* #301: (@34[3] += @18) */
  for (rr=w34+3, ss=(&w18); rr!=w34+4; rr+=1) *rr += *ss++;
  /* #302: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #303: @8 = (@8*@22) */
  w8 *= w22;
  /* #304: @18 = (@18-@8) */
  w18 -= w8;
  /* #305: (@34[2] += @18) */
  for (rr=w34+2, ss=(&w18); rr!=w34+3; rr+=1) *rr += *ss++;
  /* #306: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #307: @6 = (@6*@21) */
  w6 *= w21;
  /* #308: @18 = (@18-@6) */
  w18 -= w6;
  /* #309: (@34[1] += @18) */
  for (rr=w34+1, ss=(&w18); rr!=w34+2; rr+=1) *rr += *ss++;
  /* #310: @0 = (@0*@20) */
  w0 *= w20;
  /* #311: @3 = (@3*@0) */
  w3 *= w0;
  /* #312: @18 = (@18-@3) */
  w18 -= w3;
  /* #313: (@34[0] += @18) */
  for (rr=w34+0, ss=(&w18); rr!=w34+1; rr+=1) *rr += *ss++;
  /* #314: @18 = @34[0] */
  for (rr=(&w18), ss=w34+0; ss!=w34+1; ss+=1) *rr++ = *ss;
  /* #315: (@32[16] = @18) */
  for (rr=w32+16, ss=(&w18); rr!=w32+17; rr+=1) *rr = *ss++;
  /* #316: @18 = @34[1] */
  for (rr=(&w18), ss=w34+1; ss!=w34+2; ss+=1) *rr++ = *ss;
  /* #317: (@32[17] = @18) */
  for (rr=w32+17, ss=(&w18); rr!=w32+18; rr+=1) *rr = *ss++;
  /* #318: @18 = @34[2] */
  for (rr=(&w18), ss=w34+2; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #319: (@32[18] = @18) */
  for (rr=w32+18, ss=(&w18); rr!=w32+19; rr+=1) *rr = *ss++;
  /* #320: @18 = @34[3] */
  for (rr=(&w18), ss=w34+3; ss!=w34+4; ss+=1) *rr++ = *ss;
  /* #321: (@32[19] = @18) */
  for (rr=w32+19, ss=(&w18); rr!=w32+20; rr+=1) *rr = *ss++;
  /* #322: @18 = @34[4] */
  for (rr=(&w18), ss=w34+4; ss!=w34+5; ss+=1) *rr++ = *ss;
  /* #323: (@32[20] = @18) */
  for (rr=w32+20, ss=(&w18); rr!=w32+21; rr+=1) *rr = *ss++;
  /* #324: @18 = @34[5] */
  for (rr=(&w18), ss=w34+5; ss!=w34+6; ss+=1) *rr++ = *ss;
  /* #325: (@32[21] = @18) */
  for (rr=w32+21, ss=(&w18); rr!=w32+22; rr+=1) *rr = *ss++;
  /* #326: @18 = @34[6] */
  for (rr=(&w18), ss=w34+6; ss!=w34+7; ss+=1) *rr++ = *ss;
  /* #327: (@32[22] = @18) */
  for (rr=w32+22, ss=(&w18); rr!=w32+23; rr+=1) *rr = *ss++;
  /* #328: @18 = @34[7] */
  for (rr=(&w18), ss=w34+7; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #329: (@32[23] = @18) */
  for (rr=w32+23, ss=(&w18); rr!=w32+24; rr+=1) *rr = *ss++;
  /* #330: @28 = (@28*@4) */
  for (i=0, rr=w28; i<8; ++i) (*rr++) *= w4;
  /* #331: @4 = @28[0] */
  for (rr=(&w4), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #332: (@32[24] = @4) */
  for (rr=w32+24, ss=(&w4); rr!=w32+25; rr+=1) *rr = *ss++;
  /* #333: @4 = @28[1] */
  for (rr=(&w4), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #334: (@32[25] = @4) */
  for (rr=w32+25, ss=(&w4); rr!=w32+26; rr+=1) *rr = *ss++;
  /* #335: @4 = @28[2] */
  for (rr=(&w4), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #336: (@32[26] = @4) */
  for (rr=w32+26, ss=(&w4); rr!=w32+27; rr+=1) *rr = *ss++;
  /* #337: @4 = @28[3] */
  for (rr=(&w4), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #338: (@32[27] = @4) */
  for (rr=w32+27, ss=(&w4); rr!=w32+28; rr+=1) *rr = *ss++;
  /* #339: @4 = @28[4] */
  for (rr=(&w4), ss=w28+4; ss!=w28+5; ss+=1) *rr++ = *ss;
  /* #340: (@32[28] = @4) */
  for (rr=w32+28, ss=(&w4); rr!=w32+29; rr+=1) *rr = *ss++;
  /* #341: @4 = @28[5] */
  for (rr=(&w4), ss=w28+5; ss!=w28+6; ss+=1) *rr++ = *ss;
  /* #342: (@32[29] = @4) */
  for (rr=w32+29, ss=(&w4); rr!=w32+30; rr+=1) *rr = *ss++;
  /* #343: @4 = @28[6] */
  for (rr=(&w4), ss=w28+6; ss!=w28+7; ss+=1) *rr++ = *ss;
  /* #344: (@32[30] = @4) */
  for (rr=w32+30, ss=(&w4); rr!=w32+31; rr+=1) *rr = *ss++;
  /* #345: @4 = @28[7] */
  for (rr=(&w4), ss=w28+7; ss!=w28+8; ss+=1) *rr++ = *ss;
  /* #346: (@32[31] = @4) */
  for (rr=w32+31, ss=(&w4); rr!=w32+32; rr+=1) *rr = *ss++;
  /* #347: @4 = ones(6x1,1nz) */
  w4 = 1.;
  /* #348: {NULL, NULL, NULL, @18, NULL} = vertsplit(@4) */
  w18 = w4;
  /* #349: @29 = (@18*@29) */
  for (i=0, rr=w29, cs=w29; i<8; ++i) (*rr++)  = (w18*(*cs++));
  /* #350: @29 = @29' */
  /* #351: @4 = @29[7] */
  for (rr=(&w4), ss=w29+7; ss!=w29+8; ss+=1) *rr++ = *ss;
  /* #352: @28 = @1; (@28[7] += @4) */
  casadi_copy(w1, 8, w28);
  for (rr=w28+7, ss=(&w4); rr!=w28+8; rr+=1) *rr += *ss++;
  /* #353: (@29[7] = @19) */
  for (rr=w29+7, ss=(&w19); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #354: @4 = @29[6] */
  for (rr=(&w4), ss=w29+6; ss!=w29+7; ss+=1) *rr++ = *ss;
  /* #355: (@28[6] += @4) */
  for (rr=w28+6, ss=(&w4); rr!=w28+7; rr+=1) *rr += *ss++;
  /* #356: (@29[6] = @19) */
  for (rr=w29+6, ss=(&w19); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #357: @4 = @29[5] */
  for (rr=(&w4), ss=w29+5; ss!=w29+6; ss+=1) *rr++ = *ss;
  /* #358: (@28[5] += @4) */
  for (rr=w28+5, ss=(&w4); rr!=w28+6; rr+=1) *rr += *ss++;
  /* #359: (@29[5] = @19) */
  for (rr=w29+5, ss=(&w19); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #360: @4 = @29[4] */
  for (rr=(&w4), ss=w29+4; ss!=w29+5; ss+=1) *rr++ = *ss;
  /* #361: (@28[4] += @4) */
  for (rr=w28+4, ss=(&w4); rr!=w28+5; rr+=1) *rr += *ss++;
  /* #362: (@29[4] = @19) */
  for (rr=w29+4, ss=(&w19); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #363: @4 = @29[3] */
  for (rr=(&w4), ss=w29+3; ss!=w29+4; ss+=1) *rr++ = *ss;
  /* #364: (@28[3] += @4) */
  for (rr=w28+3, ss=(&w4); rr!=w28+4; rr+=1) *rr += *ss++;
  /* #365: (@29[3] = @19) */
  for (rr=w29+3, ss=(&w19); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #366: @4 = @29[2] */
  for (rr=(&w4), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #367: (@28[2] += @4) */
  for (rr=w28+2, ss=(&w4); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #368: (@29[2] = @19) */
  for (rr=w29+2, ss=(&w19); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #369: @4 = @29[1] */
  for (rr=(&w4), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #370: (@28[1] += @4) */
  for (rr=w28+1, ss=(&w4); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #371: (@29[1] = @19) */
  for (rr=w29+1, ss=(&w19); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #372: @19 = @29[0] */
  for (rr=(&w19), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #373: (@28[0] += @19) */
  for (rr=w28+0, ss=(&w19); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #374: @19 = @28[7] */
  for (rr=(&w19), ss=w28+7; ss!=w28+8; ss+=1) *rr++ = *ss;
  /* #375: @19 = (-@19) */
  w19 = (- w19 );
  /* #376: @4 = @28[0] */
  for (rr=(&w4), ss=w28+0; ss!=w28+1; ss+=1) *rr++ = *ss;
  /* #377: @3 = @28[1] */
  for (rr=(&w3), ss=w28+1; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #378: @3 = (@4+@3) */
  w3  = (w4+w3);
  /* #379: @0 = @28[2] */
  for (rr=(&w0), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #380: @0 = (@3+@0) */
  w0  = (w3+w0);
  /* #381: @20 = @28[3] */
  for (rr=(&w20), ss=w28+3; ss!=w28+4; ss+=1) *rr++ = *ss;
  /* #382: @20 = (@0+@20) */
  w20  = (w0+w20);
  /* #383: @6 = @28[4] */
  for (rr=(&w6), ss=w28+4; ss!=w28+5; ss+=1) *rr++ = *ss;
  /* #384: @6 = (@20+@6) */
  w6  = (w20+w6);
  /* #385: @21 = @28[5] */
  for (rr=(&w21), ss=w28+5; ss!=w28+6; ss+=1) *rr++ = *ss;
  /* #386: @21 = (@6+@21) */
  w21  = (w6+w21);
  /* #387: @8 = @28[6] */
  for (rr=(&w8), ss=w28+6; ss!=w28+7; ss+=1) *rr++ = *ss;
  /* #388: @8 = (@21+@8) */
  w8  = (w21+w8);
  /* #389: @19 = (@19-@8) */
  w19 -= w8;
  /* #390: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #391: @17 = (@17*@19) */
  w17 *= w19;
  /* #392: (@1[7] += @17) */
  for (rr=w1+7, ss=(&w17); rr!=w1+8; rr+=1) *rr += *ss++;
  /* #393: @8 = (@26*@8) */
  w8  = (w26*w8);
  /* #394: @15 = (@15*@8) */
  w15 *= w8;
  /* #395: @17 = (@17-@15) */
  w17 -= w15;
  /* #396: (@1[6] += @17) */
  for (rr=w1+6, ss=(&w17); rr!=w1+7; rr+=1) *rr += *ss++;
  /* #397: @21 = (@26*@21) */
  w21  = (w26*w21);
  /* #398: @13 = (@13*@21) */
  w13 *= w21;
  /* #399: @17 = (@17-@13) */
  w17 -= w13;
  /* #400: (@1[5] += @17) */
  for (rr=w1+5, ss=(&w17); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #401: @6 = (@26*@6) */
  w6  = (w26*w6);
  /* #402: @11 = (@11*@6) */
  w11 *= w6;
  /* #403: @17 = (@17-@11) */
  w17 -= w11;
  /* #404: (@1[4] += @17) */
  for (rr=w1+4, ss=(&w17); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #405: @20 = (@26*@20) */
  w20  = (w26*w20);
  /* #406: @9 = (@9*@20) */
  w9 *= w20;
  /* #407: @17 = (@17-@9) */
  w17 -= w9;
  /* #408: (@1[3] += @17) */
  for (rr=w1+3, ss=(&w17); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #409: @0 = (@26*@0) */
  w0  = (w26*w0);
  /* #410: @7 = (@7*@0) */
  w7 *= w0;
  /* #411: @17 = (@17-@7) */
  w17 -= w7;
  /* #412: (@1[2] += @17) */
  for (rr=w1+2, ss=(&w17); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #413: @3 = (@26*@3) */
  w3  = (w26*w3);
  /* #414: @5 = (@5*@3) */
  w5 *= w3;
  /* #415: @17 = (@17-@5) */
  w17 -= w5;
  /* #416: (@1[1] += @17) */
  for (rr=w1+1, ss=(&w17); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #417: @26 = (@26*@4) */
  w26 *= w4;
  /* #418: @2 = (@2*@26) */
  w2 *= w26;
  /* #419: @17 = (@17-@2) */
  w17 -= w2;
  /* #420: (@1[0] += @17) */
  for (rr=w1+0, ss=(&w17); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #421: @17 = @1[0] */
  for (rr=(&w17), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #422: (@32[32] = @17) */
  for (rr=w32+32, ss=(&w17); rr!=w32+33; rr+=1) *rr = *ss++;
  /* #423: @17 = @1[1] */
  for (rr=(&w17), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #424: (@32[33] = @17) */
  for (rr=w32+33, ss=(&w17); rr!=w32+34; rr+=1) *rr = *ss++;
  /* #425: @17 = @1[2] */
  for (rr=(&w17), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #426: (@32[34] = @17) */
  for (rr=w32+34, ss=(&w17); rr!=w32+35; rr+=1) *rr = *ss++;
  /* #427: @17 = @1[3] */
  for (rr=(&w17), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #428: (@32[35] = @17) */
  for (rr=w32+35, ss=(&w17); rr!=w32+36; rr+=1) *rr = *ss++;
  /* #429: @17 = @1[4] */
  for (rr=(&w17), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #430: (@32[36] = @17) */
  for (rr=w32+36, ss=(&w17); rr!=w32+37; rr+=1) *rr = *ss++;
  /* #431: @17 = @1[5] */
  for (rr=(&w17), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #432: (@32[37] = @17) */
  for (rr=w32+37, ss=(&w17); rr!=w32+38; rr+=1) *rr = *ss++;
  /* #433: @17 = @1[6] */
  for (rr=(&w17), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #434: (@32[38] = @17) */
  for (rr=w32+38, ss=(&w17); rr!=w32+39; rr+=1) *rr = *ss++;
  /* #435: @17 = @1[7] */
  for (rr=(&w17), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #436: (@32[39] = @17) */
  for (rr=w32+39, ss=(&w17); rr!=w32+40; rr+=1) *rr = *ss++;
  /* #437: @30 = (@30*@18) */
  for (i=0, rr=w30; i<8; ++i) (*rr++) *= w18;
  /* #438: @18 = @30[0] */
  for (rr=(&w18), ss=w30+0; ss!=w30+1; ss+=1) *rr++ = *ss;
  /* #439: (@32[40] = @18) */
  for (rr=w32+40, ss=(&w18); rr!=w32+41; rr+=1) *rr = *ss++;
  /* #440: @18 = @30[1] */
  for (rr=(&w18), ss=w30+1; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #441: (@32[41] = @18) */
  for (rr=w32+41, ss=(&w18); rr!=w32+42; rr+=1) *rr = *ss++;
  /* #442: @18 = @30[2] */
  for (rr=(&w18), ss=w30+2; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #443: (@32[42] = @18) */
  for (rr=w32+42, ss=(&w18); rr!=w32+43; rr+=1) *rr = *ss++;
  /* #444: @18 = @30[3] */
  for (rr=(&w18), ss=w30+3; ss!=w30+4; ss+=1) *rr++ = *ss;
  /* #445: (@32[43] = @18) */
  for (rr=w32+43, ss=(&w18); rr!=w32+44; rr+=1) *rr = *ss++;
  /* #446: @18 = @30[4] */
  for (rr=(&w18), ss=w30+4; ss!=w30+5; ss+=1) *rr++ = *ss;
  /* #447: (@32[44] = @18) */
  for (rr=w32+44, ss=(&w18); rr!=w32+45; rr+=1) *rr = *ss++;
  /* #448: @18 = @30[5] */
  for (rr=(&w18), ss=w30+5; ss!=w30+6; ss+=1) *rr++ = *ss;
  /* #449: (@32[45] = @18) */
  for (rr=w32+45, ss=(&w18); rr!=w32+46; rr+=1) *rr = *ss++;
  /* #450: @18 = @30[6] */
  for (rr=(&w18), ss=w30+6; ss!=w30+7; ss+=1) *rr++ = *ss;
  /* #451: (@32[46] = @18) */
  for (rr=w32+46, ss=(&w18); rr!=w32+47; rr+=1) *rr = *ss++;
  /* #452: @18 = @30[7] */
  for (rr=(&w18), ss=w30+7; ss!=w30+8; ss+=1) *rr++ = *ss;
  /* #453: (@32[47] = @18) */
  for (rr=w32+47, ss=(&w18); rr!=w32+48; rr+=1) *rr = *ss++;
  /* #454: output[1][0] = @32 */
  casadi_copy(w32, 50, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
