/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun:(i0[16],i1[2],i2[],i3[],i4[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+28, *w21=w+36, *w22=w+44;
  /* #0: @0 = 0.0625 */
  w0 = 6.2500000000000000e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 8, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #5: @5 = @1[1] */
  for (rr=(&w5), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #7: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #8: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #9: @4 = (@4+@7) */
  w4 += w7;
  /* #10: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #12: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #13: @9 = (@0*@8) */
  w9  = (w0*w8);
  /* #14: @4 = (@4+@9) */
  w4 += w9;
  /* #15: @9 = @1[3] */
  for (rr=(&w9), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@7+@9) */
  w9  = (w7+w9);
  /* #17: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #18: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #19: @4 = (@4+@11) */
  w4 += w11;
  /* #20: @11 = @1[4] */
  for (rr=(&w11), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@9+@11) */
  w11  = (w9+w11);
  /* #22: @12 = sin(@11) */
  w12 = sin( w11 );
  /* #23: @13 = (@0*@12) */
  w13  = (w0*w12);
  /* #24: @4 = (@4+@13) */
  w4 += w13;
  /* #25: @13 = @1[5] */
  for (rr=(&w13), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #26: @13 = (@11+@13) */
  w13  = (w11+w13);
  /* #27: @14 = sin(@13) */
  w14 = sin( w13 );
  /* #28: @15 = (@0*@14) */
  w15  = (w0*w14);
  /* #29: @4 = (@4+@15) */
  w4 += w15;
  /* #30: @15 = @1[6] */
  for (rr=(&w15), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #31: @15 = (@13+@15) */
  w15  = (w13+w15);
  /* #32: @16 = sin(@15) */
  w16 = sin( w15 );
  /* #33: @17 = (@0*@16) */
  w17  = (w0*w16);
  /* #34: @4 = (@4+@17) */
  w4 += w17;
  /* #35: @17 = @1[7] */
  for (rr=(&w17), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #36: @17 = (@15+@17) */
  w17  = (w15+w17);
  /* #37: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #38: @19 = (@0*@18) */
  w19  = (w0*w18);
  /* #39: @4 = (@4+@19) */
  w4 += w19;
  /* #40: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #41: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #42: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #43: @4 = (-@2) */
  w4 = (- w2 );
  /* #44: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #45: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #46: @4 = (@4-@5) */
  w4 -= w5;
  /* #47: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #48: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #49: @4 = (@4-@7) */
  w4 -= w7;
  /* #50: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #51: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #52: @4 = (@4-@9) */
  w4 -= w9;
  /* #53: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #54: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #55: @4 = (@4-@11) */
  w4 -= w11;
  /* #56: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #57: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #58: @4 = (@4-@13) */
  w4 -= w13;
  /* #59: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #60: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #61: @4 = (@4-@15) */
  w4 -= w15;
  /* #62: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #63: @0 = (@0*@17) */
  w0 *= w17;
  /* #64: @4 = (@4-@0) */
  w4 -= w0;
  /* #65: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #66: @4 = 0 */
  w4 = 0.;
  /* #67: @1 = zeros(8x1) */
  casadi_clear(w1, 8);
  /* #68: @20 = @1; (@20[7] += @0) */
  casadi_copy(w1, 8, w20);
  for (rr=w20+7, ss=(&w0); rr!=w20+8; rr+=1) *rr += *ss++;
  /* #69: @0 = (@0+@15) */
  w0 += w15;
  /* #70: (@20[6] += @0) */
  for (rr=w20+6, ss=(&w0); rr!=w20+7; rr+=1) *rr += *ss++;
  /* #71: @0 = (@0+@13) */
  w0 += w13;
  /* #72: (@20[5] += @0) */
  for (rr=w20+5, ss=(&w0); rr!=w20+6; rr+=1) *rr += *ss++;
  /* #73: @0 = (@0+@11) */
  w0 += w11;
  /* #74: (@20[4] += @0) */
  for (rr=w20+4, ss=(&w0); rr!=w20+5; rr+=1) *rr += *ss++;
  /* #75: @0 = (@0+@9) */
  w0 += w9;
  /* #76: (@20[3] += @0) */
  for (rr=w20+3, ss=(&w0); rr!=w20+4; rr+=1) *rr += *ss++;
  /* #77: @0 = (@0+@7) */
  w0 += w7;
  /* #78: (@20[2] += @0) */
  for (rr=w20+2, ss=(&w0); rr!=w20+3; rr+=1) *rr += *ss++;
  /* #79: @0 = (@0+@5) */
  w0 += w5;
  /* #80: (@20[1] += @0) */
  for (rr=w20+1, ss=(&w0); rr!=w20+2; rr+=1) *rr += *ss++;
  /* #81: @0 = (@0+@2) */
  w0 += w2;
  /* #82: (@20[0] += @0) */
  for (rr=w20+0, ss=(&w0); rr!=w20+1; rr+=1) *rr += *ss++;
  /* #83: @0 = @20[0] */
  for (rr=(&w0), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #84: @21 = @1; (@21[0] = @0) */
  casadi_copy(w1, 8, w21);
  for (rr=w21+0, ss=(&w0); rr!=w21+1; rr+=1) *rr = *ss++;
  /* #85: @0 = @20[1] */
  for (rr=(&w0), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #86: (@21[1] = @0) */
  for (rr=w21+1, ss=(&w0); rr!=w21+2; rr+=1) *rr = *ss++;
  /* #87: @0 = @20[2] */
  for (rr=(&w0), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #88: (@21[2] = @0) */
  for (rr=w21+2, ss=(&w0); rr!=w21+3; rr+=1) *rr = *ss++;
  /* #89: @0 = @20[3] */
  for (rr=(&w0), ss=w20+3; ss!=w20+4; ss+=1) *rr++ = *ss;
  /* #90: (@21[3] = @0) */
  for (rr=w21+3, ss=(&w0); rr!=w21+4; rr+=1) *rr = *ss++;
  /* #91: @0 = @20[4] */
  for (rr=(&w0), ss=w20+4; ss!=w20+5; ss+=1) *rr++ = *ss;
  /* #92: (@21[4] = @0) */
  for (rr=w21+4, ss=(&w0); rr!=w21+5; rr+=1) *rr = *ss++;
  /* #93: @0 = @20[5] */
  for (rr=(&w0), ss=w20+5; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #94: (@21[5] = @0) */
  for (rr=w21+5, ss=(&w0); rr!=w21+6; rr+=1) *rr = *ss++;
  /* #95: @0 = @20[6] */
  for (rr=(&w0), ss=w20+6; ss!=w20+7; ss+=1) *rr++ = *ss;
  /* #96: (@21[6] = @0) */
  for (rr=w21+6, ss=(&w0); rr!=w21+7; rr+=1) *rr = *ss++;
  /* #97: @0 = @20[7] */
  for (rr=(&w0), ss=w20+7; ss!=w20+8; ss+=1) *rr++ = *ss;
  /* #98: (@21[7] = @0) */
  for (rr=w21+7, ss=(&w0); rr!=w21+8; rr+=1) *rr = *ss++;
  /* #99: @21 = @21' */
  /* #100: @20 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+8 : 0, 8, w20);
  /* #101: @0 = mac(@21,@20,@4) */
  casadi_copy((&w4), 1, (&w0));
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w20+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #102: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #103: @0 = -0.0625 */
  w0 = -6.2500000000000000e-02;
  /* #104: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #105: @2 = (-@18) */
  w2 = (- w18 );
  /* #106: @21 = @1; (@21[7] += @2) */
  casadi_copy(w1, 8, w21);
  for (rr=w21+7, ss=(&w2); rr!=w21+8; rr+=1) *rr += *ss++;
  /* #107: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #108: @16 = (-@16) */
  w16 = (- w16 );
  /* #109: @16 = (@16-@18) */
  w16 -= w18;
  /* #110: (@21[6] += @16) */
  for (rr=w21+6, ss=(&w16); rr!=w21+7; rr+=1) *rr += *ss++;
  /* #111: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #112: @16 = (@16-@14) */
  w16 -= w14;
  /* #113: (@21[5] += @16) */
  for (rr=w21+5, ss=(&w16); rr!=w21+6; rr+=1) *rr += *ss++;
  /* #114: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #115: @16 = (@16-@12) */
  w16 -= w12;
  /* #116: (@21[4] += @16) */
  for (rr=w21+4, ss=(&w16); rr!=w21+5; rr+=1) *rr += *ss++;
  /* #117: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #118: @16 = (@16-@10) */
  w16 -= w10;
  /* #119: (@21[3] += @16) */
  for (rr=w21+3, ss=(&w16); rr!=w21+4; rr+=1) *rr += *ss++;
  /* #120: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #121: @16 = (@16-@8) */
  w16 -= w8;
  /* #122: (@21[2] += @16) */
  for (rr=w21+2, ss=(&w16); rr!=w21+3; rr+=1) *rr += *ss++;
  /* #123: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #124: @16 = (@16-@6) */
  w16 -= w6;
  /* #125: (@21[1] += @16) */
  for (rr=w21+1, ss=(&w16); rr!=w21+2; rr+=1) *rr += *ss++;
  /* #126: @0 = (@0*@3) */
  w0 *= w3;
  /* #127: @16 = (@16-@0) */
  w16 -= w0;
  /* #128: (@21[0] += @16) */
  for (rr=w21+0, ss=(&w16); rr!=w21+1; rr+=1) *rr += *ss++;
  /* #129: @16 = @21[0] */
  for (rr=(&w16), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #130: (@1[0] = @16) */
  for (rr=w1+0, ss=(&w16); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #131: @16 = @21[1] */
  for (rr=(&w16), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #132: (@1[1] = @16) */
  for (rr=w1+1, ss=(&w16); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #133: @16 = @21[2] */
  for (rr=(&w16), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #134: (@1[2] = @16) */
  for (rr=w1+2, ss=(&w16); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #135: @16 = @21[3] */
  for (rr=(&w16), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #136: (@1[3] = @16) */
  for (rr=w1+3, ss=(&w16); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #137: @16 = @21[4] */
  for (rr=(&w16), ss=w21+4; ss!=w21+5; ss+=1) *rr++ = *ss;
  /* #138: (@1[4] = @16) */
  for (rr=w1+4, ss=(&w16); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #139: @16 = @21[5] */
  for (rr=(&w16), ss=w21+5; ss!=w21+6; ss+=1) *rr++ = *ss;
  /* #140: (@1[5] = @16) */
  for (rr=w1+5, ss=(&w16); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #141: @16 = @21[6] */
  for (rr=(&w16), ss=w21+6; ss!=w21+7; ss+=1) *rr++ = *ss;
  /* #142: (@1[6] = @16) */
  for (rr=w1+6, ss=(&w16); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #143: @16 = @21[7] */
  for (rr=(&w16), ss=w21+7; ss!=w21+8; ss+=1) *rr++ = *ss;
  /* #144: (@1[7] = @16) */
  for (rr=w1+7, ss=(&w16); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #145: @1 = @1' */
  /* #146: @4 = mac(@1,@20,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*8; k<8; ++k) *rr += ss[k*1]**tt++;
  /* #147: output[0][3] = @4 */
  if (res[0]) res[0][3] = w4;
  /* #148: @22 = input[1][0] */
  casadi_copy(arg[1], 2, w22);
  /* #149: output[0][4] = @22 */
  if (res[0]) casadi_copy(w22, 2, res[0]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 46;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 46*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
