/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[12] = {16, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s4[3] = {1, 0, 0};

/* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt:(i0[16],i1[],i2[],i3[])->(o0,o1[16x1,8nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+19;
  /* #0: @0 = 0.0625 */
  w0 = 6.2500000000000000e-02;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 8, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #4: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #5: @4 = @1[1] */
  for (rr=(&w4), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #6: @4 = (@2+@4) */
  w4  = (w2+w4);
  /* #7: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #8: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #9: @3 = (@3+@5) */
  w3 += w5;
  /* #10: @5 = @1[2] */
  for (rr=(&w5), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @5 = (@4+@5) */
  w5  = (w4+w5);
  /* #12: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #13: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #14: @3 = (@3+@6) */
  w3 += w6;
  /* #15: @6 = @1[3] */
  for (rr=(&w6), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @6 = (@5+@6) */
  w6  = (w5+w6);
  /* #17: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #18: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #19: @3 = (@3+@7) */
  w3 += w7;
  /* #20: @7 = @1[4] */
  for (rr=(&w7), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #21: @7 = (@6+@7) */
  w7  = (w6+w7);
  /* #22: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #23: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #24: @3 = (@3+@8) */
  w3 += w8;
  /* #25: @8 = @1[5] */
  for (rr=(&w8), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #26: @8 = (@7+@8) */
  w8  = (w7+w8);
  /* #27: @9 = sin(@8) */
  w9 = sin( w8 );
  /* #28: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #29: @3 = (@3+@9) */
  w3 += w9;
  /* #30: @9 = @1[6] */
  for (rr=(&w9), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #31: @9 = (@8+@9) */
  w9  = (w8+w9);
  /* #32: @10 = sin(@9) */
  w10 = sin( w9 );
  /* #33: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #34: @3 = (@3+@10) */
  w3 += w10;
  /* #35: @10 = @1[7] */
  for (rr=(&w10), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #36: @10 = (@9+@10) */
  w10  = (w9+w10);
  /* #37: @11 = sin(@10) */
  w11 = sin( w10 );
  /* #38: @11 = (@0*@11) */
  w11  = (w0*w11);
  /* #39: @3 = (@3+@11) */
  w3 += w11;
  /* #40: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #41: @1 = zeros(16x1,8nz) */
  casadi_clear(w1, 8);
  /* #42: @12 = zeros(8x1) */
  casadi_clear(w12, 8);
  /* #43: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #44: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #45: (@12[7] += @10) */
  for (rr=w12+7, ss=(&w10); rr!=w12+8; rr+=1) *rr += *ss++;
  /* #46: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #47: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #48: @10 = (@10+@9) */
  w10 += w9;
  /* #49: (@12[6] += @10) */
  for (rr=w12+6, ss=(&w10); rr!=w12+7; rr+=1) *rr += *ss++;
  /* #50: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #51: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #52: @10 = (@10+@8) */
  w10 += w8;
  /* #53: (@12[5] += @10) */
  for (rr=w12+5, ss=(&w10); rr!=w12+6; rr+=1) *rr += *ss++;
  /* #54: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #55: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #56: @10 = (@10+@7) */
  w10 += w7;
  /* #57: (@12[4] += @10) */
  for (rr=w12+4, ss=(&w10); rr!=w12+5; rr+=1) *rr += *ss++;
  /* #58: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #59: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #60: @10 = (@10+@6) */
  w10 += w6;
  /* #61: (@12[3] += @10) */
  for (rr=w12+3, ss=(&w10); rr!=w12+4; rr+=1) *rr += *ss++;
  /* #62: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #63: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #64: @10 = (@10+@5) */
  w10 += w5;
  /* #65: (@12[2] += @10) */
  for (rr=w12+2, ss=(&w10); rr!=w12+3; rr+=1) *rr += *ss++;
  /* #66: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #67: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #68: @10 = (@10+@4) */
  w10 += w4;
  /* #69: (@12[1] += @10) */
  for (rr=w12+1, ss=(&w10); rr!=w12+2; rr+=1) *rr += *ss++;
  /* #70: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #71: @0 = (@0*@2) */
  w0 *= w2;
  /* #72: @10 = (@10+@0) */
  w10 += w0;
  /* #73: (@12[0] += @10) */
  for (rr=w12+0, ss=(&w10); rr!=w12+1; rr+=1) *rr += *ss++;
  /* #74: @10 = @12[0] */
  for (rr=(&w10), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #75: (@1[0] = @10) */
  for (rr=w1+0, ss=(&w10); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #76: @10 = @12[1] */
  for (rr=(&w10), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #77: (@1[1] = @10) */
  for (rr=w1+1, ss=(&w10); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #78: @10 = @12[2] */
  for (rr=(&w10), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #79: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #80: @10 = @12[3] */
  for (rr=(&w10), ss=w12+3; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #81: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #82: @10 = @12[4] */
  for (rr=(&w10), ss=w12+4; ss!=w12+5; ss+=1) *rr++ = *ss;
  /* #83: (@1[4] = @10) */
  for (rr=w1+4, ss=(&w10); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #84: @10 = @12[5] */
  for (rr=(&w10), ss=w12+5; ss!=w12+6; ss+=1) *rr++ = *ss;
  /* #85: (@1[5] = @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #86: @10 = @12[6] */
  for (rr=(&w10), ss=w12+6; ss!=w12+7; ss+=1) *rr++ = *ss;
  /* #87: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #88: @10 = @12[7] */
  for (rr=(&w10), ss=w12+7; ss!=w12+8; ss+=1) *rr++ = *ss;
  /* #89: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #90: output[1][0] = @1 */
  casadi_copy(w1, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 27;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_8_links_8_4_p_10_10_10_015000000000000005_FULL_CONDENSING_HPIPM_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 27*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
